//languageSequence = ['en', 'es', 'de', 'it'];
const countries = {
    "AF": ["Afghanistan","Afganistán","Afghanistan","Afghanistan"],
    "AX": ["Åland Islands","Islas Åland","Åland-Inseln","Isole Åland"],
    "AL": ["Albania","Albania","Albanien","Albania"],
    "DZ": ["Algeria","Argelia","Algerien","Algeria"],
    "AS": ["American Samoa","Samoa Americana","Amerikanisch-Samoa","American Samoa"],
    "AD": ["Andorra","Andorra","Andorra","Andorra"],
    "AO": ["Angola","Angola","Angola","Angola"],
    "AI": ["Anguilla","Anguila","Anguilla","Anguilla"],
    "AQ": ["Antarctica","Antártida","Antarktis","Antarctica"],
    "AG": ["Antigua and Barbuda","Antigua y Barbuda","Antigua und Barbuda","Antigua e Barbuda"],
    "AR": ["Argentina","Argentina","Argentinien","Argentina"],
    "AM": ["Armenia","Armenia","Armenien","Armenia"],
    "AW": ["Aruba","Aruba","Aruba","Aruba"],
    "AU": ["Australia","Australia","Australien","Australia"],
    "AT": ["Austria","Austria","Österreich","Austria"],
    "AZ": ["Azerbaijan","Azerbaiyán","Aserbaidschan","Azerbaijan"],
    "BS": ["Bahamas","Bahamas","Bahamas","Bahamas"],
    "BH": ["Bahrain","Bahrein","Bahrain","Bahrain"],
    "BD": ["Bangladesh","Bangladesh","Bangladesch","Bangladesh"],
    "BB": ["Barbados","Barbados","Barbados","Barbados"],
    "BY": ["Belarus","Bielorrusia","Belarus","Bielorussia"],
    "BE": ["Belgium","Bélgica","Belgien","Belgio"],
    "BZ": ["Belize","Belice","Belize","Belize"],
    "BJ": ["Benin","Benin","Benin","Benin"],
    "BM": ["Bermuda","Bermuda","Bermudas","Bermuda"],
    "BT": ["Bhutan","Bhután","Bhutan","Bhutan"],
    "BO": ["Bolivia","Bolivia","Bolivien","Bolivia"],
    "BA": ["Bosnia and Herzegovina","Bosnia y Herzegovina","Bosnien und Herzegowina","Bosnia ed Erzegovina"],
    "BW": ["Botswana","Botswana","Botswana","Botswana"],
    "BV": ["Bouvet Island","Isla Bouvet","Bouvetinsel","Isola di Bouvet"],
    "BR": ["Brazil","Brasil","Brasilien","Brasile"],
    "IO": ["British Indian Ocean Territory","Territorio Británico del Océano Índico","Britisches Territorium im Indischen Ozean","British Indian Ocean Territory"],
    "BN": ["Brunei Darussalam","Brunei Darussalam","Brunei Darussalam","Brunei Darussalam"],
    "BG": ["Bulgaria","Bulgaria","Bulgarien","Bulgaria"],
    "BF": ["Burkina Faso","Burkina Faso","Burkina Faso","Burkina Faso"],
    "BI": ["Burundi","Burundi","Burundi","Burundi"],
    "KH": ["Cambodia","Camboya","Kambodscha","Cambogia"],
    "CM": ["Cameroon","Camerún","Kamerun","Camerun"],
    "CA": ["Canada","Canadá","Kanada","Canada"],
    "CV": ["Cape Verde","Cabo Verde","Kapverdische Inseln","Capo Verde"],
    "KY": ["Cayman Islands","Islas Caimán","Cayman Islands","Isole Cayman"],
    "CF": ["Central African Republic","República Centroafricana","Zentralafrikanische Republik","Repubblica Centrafricana"],
    "TD": ["Chad","República Centroafricana","Tschad","Chad"],
    "CL": ["Chile","Chile","Chile","Cile"],
    "CN": ["China","China","China","Cina"],
    "CX": ["Christmas Island","Isla de Navidad","Weihnachtsinsel","Isola di Natale"],
    "CC": ["Cocos (Keeling) Islands","Islas Cocos (Keeling)","Cocos (Keeling) Islands","Isole Cocos (Keeling)"],
    "CO": ["Colombia","Colombia","Kolumbien","Colombia"],
    "KM": ["Comoros","Comoras","Komoren","Comore"],
    "CG": ["Congo","Congo","Kongo","Congo"],
    "CD": ["Congo, The Democratic Republic of the","Congo, República Democrática del","Kongo, Demokratische Republik","Congo, Repubblica Democratica del"],
    "CK": ["Cook Islands","Islas Cook","Cookinseln","Isole Cook"],
    "CR": ["Costa Rica","Costa Rica","Costa Rica","Costa Rica"],
    "CI": ["Cote D'Ivoire","Costa de Marfil","Elfenbeinküste","Costa d'Avorio"],
    "HR": ["Croatia","Croacia","Kroatien","Croazia"],
    "CU": ["Cuba","Cuba","Kuba","Cuba"],
    "CY": ["Cyprus","Chipre","Zypern","Cipro"],
    "CZ": ["Czech Republic","República Checa","Tschechische Republik","Repubblica ceca"],
    "DK": ["Denmark","Dinamarca","Dänemark","Danimarca"],
    "DJ": ["Djibouti","Djibouti","Dschibuti","Djibouti"],
    "DM": ["Dominica","Dominica","Dominica","Dominica"],
    "DO": ["Dominican Republic","República Dominicana","Dominikanische Republik","Repubblica Dominicana"],
    "EC": ["Ecuador","Ecuador","Ecuador","Ecuador"],
    "EG": ["Egypt","Egipto","Ägypten","Egitto"],
    "SV": ["El Salvador","El Salvador","El Salvador","El Salvador"],
    "GQ": ["Equatorial Guinea","Guinea Ecuatorial","Äquatorialguinea","Guinea equatoriale"],
    "ER": ["Eritrea","Eritrea","Eritrea","Eritrea"],
    "EE": ["Estonia","Estonia","Estland","Estonia"],
    "ET": ["Ethiopia","Etiopía","Äthiopien","Etiopia"],
    "FK": ["Falkland Islands (Malvinas)","Islas Falkland (Malvinas)","Falklandinseln (Malvinas)","Isole Falkland (Malvinas)"],
    "FO": ["Faroe Islands","Islas Feroe","Färöer Inseln","Isole Faroe"],
    "FJ": ["Fiji","Fiji","Fidschi","Fiji"],
    "FI": ["Finland","Finlandia","Finnland","Finlandia"],
    "FR": ["France","Francia","Frankreich","Francia"],
    "GF": ["French Guiana","Guayana Francesa","Französisch-Guayana","Guyana francese"],
    "PF": ["French Polynesia","Polinesia Francesa","Französisch-Polynesien","Polinesia Francese"],
    "TF": ["French Southern Territories","Territorios Australes Franceses","Französische Südgebiete","Territori francesi meridionali"],
    "GA": ["Gabon","Gabón","Gabun","Gabon"],
    "GM": ["Gambia","Gambia","Gambia","Gambia"],
    "GE": ["Georgia","Georgia","Georgien","Georgia"],
    "DE": ["Germany", "Alemania", "Deutschland", "Germania"],
    "GH": ["Ghana","Ghana","Ghana","Ghana"],
    "GI": ["Gibraltar","Gibraltar","Gibraltar","Gibilterra"],
    "GR": ["Greece","Grecia","Griechenland","Grecia"],
    "GL": ["Greenland","Groenlandia","Grönland","Groenlandia"],
    "GD": ["Grenada","Granada","Grenada","Grenada"],
    "GP": ["Guadeloupe","Guadalupe","Guadeloupe","Guadalupa"],
    "GU": ["Guam","Guam","Guam","Guam"],
    "GT": ["Guatemala","Guatemala","Guatemala","Guatemala"],
    "GG": ["Guernsey","Guernsey","Guernsey","Guernsey"],
    "GN": ["Guinea","Guinea","Guinea","Guinea"],
    "GW": ["Guinea-Bissau","Guinea-Bissau","Guinea-Bissau","Guinea-Bissau"],
    "GY": ["Guyana","Guyana","Guyana","Guyana"],
    "HT": ["Haiti","Haití","Haiti","Haiti"],
    "HM": ["Heard Island and Mcdonald Islands","Heard Island and Mcdonald Islands","Heard Island und McDonald Islands","Isole Heard Island e Mcdonald"],
    "VA": ["Holy See (Vatican City State)","Santa Sede (Estado de la Ciudad del Vaticano)","Heiliger Stuhl (Vatikanstadt)","Santa Sede (Stato della Città del Vaticano)"],
    "HN": ["Honduras","Honduras","Honduras","Honduras"],
    "HK": ["Hong Kong","Hong Kong","Hongkong","Hong Kong"],
    "HU": ["Hungary","Hungría","Ungarn","Ungheria"],
    "IS": ["Iceland","Islandia","Island","Islanda"],
    "IN": ["India","India","Indien","India"],
    "ID": ["Indonesia","Indonesia","Indonesien","Indonesia"],
    "IR": ["Iran, Islamic Republic Of","Irán, República Islámica del","Iran, Islamische Republik","Iran, Repubblica islamica di"],
    "IQ": ["Iraq","Iraq","Irak","Iraq"],
    "IE": ["Ireland","Irlanda","Irland","Irlanda"],
    "IM": ["Isle of Man","Isla de Man","Isle of Man","Isola di Man"],
    "IL": ["Israel","Israel","Israel","Israele"],
    "IT": ["Italy", "Italia", "Italien", "Italia"],
    "JM": ["Jamaica","Jamaica","Jamaika","Giamaica"],
    "JP": ["Japan","Japón","Japan","Giappone"],
    "JE": ["Jersey","Jersey","Jersey","Jersey"],
    "JO": ["Jordan","Jordan","Jordanien","Jordan"],
    "KZ": ["Kazakhstan","Kazajstán","Kasachstan","Kazakhstan"],
    "KE": ["Kenya","Kenia","Kenia","Kenya"],
    "KI": ["Kiribati","Kiribati","Kiribati","Kiribati"],
    "KP": ["Democratic People's Republic of Korea","República Popular Democrática de Corea","Demokratische Volksrepublik Korea","Repubblica democratica popolare di Corea"],
    "KR": ["Korea, Republic of","Corea, República de","Korea, Republik","Corea, Repubblica di"],
    "XK": ["Kosovo","Kosovo","Kosovo","Kosovo"],
    "KW": ["Kuwait","Kuwait","Kuwait","Kuwait"],
    "KG": ["Kyrgyzstan","Kirguistán","Kirgisistan","Kirghizistan"],
    "LA": ["Lao People's Democratic Republic","República Democrática Popular Lao","Demokratische Volksrepublik Laos","Repubblica democratica popolare del Laos"],
    "LV": ["Latvia","Letonia","Lettland","Lettonia"],
    "LB": ["Lebanon","Líbano","Libanon","Libano"],
    "LS": ["Lesotho","Lesotho","Lesotho","Lesotho"],
    "LR": ["Liberia","Liberia","Liberia","Liberia"],
    "LY": ["Libyan Arab Jamahiriya","Jamahiriya Árabe Libia","Libyan Arab Jamahiriya","Jamahiriya arabo libico"],
    "LI": ["Liechtenstein","Liechtenstein","Liechtenstein","Liechtenstein"],
    "LT": ["Lithuania","Lituania","Litauen","Lituania"],
    "LU": ["Luxembourg","Luxemburgo","Luxemburg","Lussemburgo"],
    "MO": ["Macao","Macao","Macao","Macao"],
    "MK": ["Macedonia, The Former Yugoslav Republic of","Macedonia, ex República Yugoslava de","Mazedonien, die ehemalige jugoslawische Republik","Macedonia, ex Repubblica jugoslava di"],
    "MG": ["Madagascar","Madagascar","Madagaskar","Madagascar"],
    "MW": ["Malawi","Malawi","Malawi","Malawi"],
    "MY": ["Malaysia","Malasia","Malaysia","Malesia"],
    "MV": ["Maldives","Maldivas","Malediven","Maldive"],
    "ML": ["Mali","Mali","Mali","Mali"],
    "MT": ["Malta","Malta","Malta","Malta"],
    "MH": ["Marshall Islands","Islas Marshall","Marshallinseln","Isole Marshall"],
    "MQ": ["Martinique","Martinica","Martinique","Martinica"],
    "MR": ["Mauritania","Mauritania","Mauretanien","Mauritania"],
    "MU": ["Mauritius","Mauricio","Mauritius","Mauritius"],
    "YT": ["Mayotte","Mayotte","Mayotte","Mayotte"],
    "MX": ["Mexico","México","Mexiko","Messico"],
    "FM": ["Micronesia, Federated States of","Micronesia, Estados Federados de","Mikronesien, Föderierte Staaten von","Micronesia, Stati federati di"],
    "MD": ["Moldova, Republic of","Moldavia, República de","Moldawien, Republik","Moldova, Repubblica di"],
    "MC": ["Monaco","Mónaco","Monaco","Monaco"],
    "MN": ["Mongolia","Mongolia","Mongolei","Mongolia"],
    "ME": ["Montenegro","Montenegro","Montenegro","Montenegro"],
    "MS": ["Montserrat","Montserrat","Montserrat","Montserrat"],
    "MA": ["Morocco","Marruecos","Marokko","Marocco"],
    "MZ": ["Mozambique","Mozambique","Mosambik","Mozambico"],
    "MM": ["Myanmar","Myanmar","Myanmar","Myanmar"],
    "NA": ["Namibia","Namibia","Namibia","Namibia"],
    "NR": ["Nauru","Nauru","Nauru","Nauru"],
    "NP": ["Nepal","Nepal","Nepal","Nepal"],
    "NL": ["Netherlands","Países Bajos","Niederlande","Paesi Bassi"],
    "AN": ["Netherlands Antilles","Antillas Holandesas","Niederländische Antillen","Antille olandesi"],
    "NC": ["New Caledonia","Nueva Caledonia","Neukaledonien","Nuova Caledonia"],
    "NZ": ["New Zealand","Nueva Zelanda","Neuseeland","Nuova Zelanda"],
    "NI": ["Nicaragua","Nicaragua","Nicaragua","Nicaragua"],
    "NE": ["Niger","Níger","Niger","Niger"],
    "NG": ["Nigeria","Nigeria","Nigeria","Nigeria"],
    "NU": ["Niue","Niue","Niue","Niue"],
    "NF": ["Norfolk Island","Isla de Norfolk","Norfolkinsel","Isola Norfolk"],
    "MP": ["Northern Mariana Islands","Islas Marianas del Norte","Nördliche Marianen","Isole Marianne settentrionali"],
    "NO": ["Norway","Noruega","Norwegen","Norvegia"],
    "OM": ["Oman","Omán","Oman","Oman"],
    "PK": ["Pakistan","Pakistán","Pakistan","Pakistan"],
    "PW": ["Palau","Palau","Palau","Palau"],
    "PS": ["Palestinian Territory, Occupied","Territorio Palestino, Ocupado","Palästinensische Gebiete, besetzte Gebiete","Territorio palestinese, occupato"],
    "PA": ["Panama","Panamá","Panama","Panama"],
    "PG": ["Papua New Guinea","Papua Nueva Guinea","Papua-Neuguinea","Papua Nuova Guinea"],
    "PY": ["Paraguay","Paraguay","Paraguay","Paraguay"],
    "PE": ["Peru","Perú","Peru","Perù"],
    "PH": ["Philippines","Filipinas","Philippinen","Filippine"],
    "PN": ["Pitcairn","Pitcairn","Pitcairn","Pitcairn"],
    "PL": ["Poland","Polonia","Polen","Polonia"],
    "PT": ["Portugal","Portugal","Portugal","Portogallo"],
    "PR": ["Puerto Rico","Puerto Rico","Puerto Rico","Porto Rico"],
    "QA": ["Qatar","Qatar","Katar","Qatar"],
    "RE": ["Reunion","Reunión","Wiedersehen","Reunion"],
    "RO": ["Romania","Rumania","Rumänien","Romania"],
    "RU": ["Russian Federation","Federación de Rusia","Russische Föderation","Federazione russa"],
    "RW": ["Rwanda","Ruanda","Ruanda","Ruanda"],
    "SH": ["Saint Helena","Santa Helena","Heilige Helena","Sant Elena"],
    "KN": ["Saint Kitts and Nevis","Saint Kitts y Nevis","St. Kitts und Nevis","Saint Kitts e Nevis"],
    "LC": ["Saint Lucia","Santa Lucía","Heilige Lucia","Santa Lucia"],
    "PM": ["Saint Pierre and Miquelon","San Pedro y Miquelón","Saint Pierre und Miquelon","Saint Pierre e Miquelon"],
    "VC": ["Saint Vincent and the Grenadines","San Vicente y las Granadinas","St. Vincent und die Grenadinen","Saint Vincent e Grenadine"],
    "WS": ["Samoa","Samoa","Samoa","Samoa"],
    "SM": ["San Marino","San Marino","San Marino","San Marino"],
    "ST": ["Sao Tome and Principe","Santo Tomé y Príncipe","Saudi Arabien","Sao Tome e Principe"],
    "SA": ["Saudi Arabia","Arabia Saudita","Saudi Arabien","Arabia Saudita"],
    "SN": ["Senegal","Senegal","Senegal","Senegal"],
    "RS": ["Serbia","Serbia","Serbien","Serbia"],
    "SC": ["Seychelles","Seychelles","Seychellen","Seychelles"],
    "SL": ["Sierra Leone","Sierra Leona","Sierra Leone","Sierra Leone"],
    "SG": ["Singapore","Singapur","Singapur","Singapore"],
    "SK": ["Slovakia","Eslovaquia","Slowakei","Slovacchia"],
    "SI": ["Slovenia","Eslovenia","Slowenien","Slovenia"],
    "SB": ["Solomon Islands","Islas Salomón","Salomonen","Isole Salomone"],
    "SO": ["Somalia","Somalia","Somalia","Somalia"],
    "ZA": ["South Africa","Sudáfrica","Südafrika","Sud Africa"],
    "GS": ["South Georgia and the South Sandwich Islands","Islas Georgia del Sur y Sandwich del Sur","Südgeorgien und die Südlichen Sandwichinseln","South Georgia and the South Sandwich Islands"],
    "ES": ["Spain","España","Spanien","Spagna"],
    "LK": ["Sri Lanka","Sri Lanka","Sri Lanka","Sri Lanka"],
    "SD": ["Sudan","Sudán","Sudan","Sudan"],
    "SR": ["Suriname","Suriname","Suriname","Suriname"],
    "SJ": ["Svalbard and Jan Mayen","Svalbard y Jan Mayen","Svalbard und Jan Mayen","Svalbard and Jan Mayen"],
    "SZ": ["Swaziland","Suazilandia","Swasiland","Swaziland"],
    "SE": ["Sweden","Suecia","Schweden","Svezia"],
    "CH": ["Switzerland","Suiza","Schweiz","Svizzera"],
    "SY": ["Syrian Arab Republic","República Árabe Siria","Arabische Republik Syrien","Repubblica araba siriana"],
    "TW": ["Taiwan","Taiwán","Taiwan","Taiwan"],
    "TJ": ["Tajikistan","Tayikistán","Tadschikistan","Tagikistan"],
    "TZ": ["Tanzania, United Republic of","Tanzania, República Unida de","Tansania, Vereinigte Republik","Tanzania, Repubblica Unita di"],
    "TH": ["Thailand","Tailandia","Thailand","Tailandia"],
    "TL": ["Timor-Leste","Timor-Leste","Timor-Leste","Timor-Leste"],
    "TG": ["Togo","Togo","Togo","Togo"],
    "TK": ["Tokelau","Tokelau","Tokelau","Tokelau"],
    "TO": ["Tonga","Tonga","Tonga","Tonga"],
    "TT": ["Trinidad and Tobago","Trinidad y Tobago","Trinidad und Tobago","Trinidad e Tobago"],
    "TN": ["Tunisia","Túnez","Tunesien","Tunisia"],
    "TR": ["Turkey","Turquía","Die Türkei","Turchia"],
    "TM": ["Turkmenistan","Turkmenistán","Turkmenistan","Turkmenistan"],
    "TC": ["Turks and Caicos Islands","Islas Turcas y Caicos","Turks und Caicosinseln","Isole Turks e Caicos"],
    "TV": ["Tuvalu","Tuvalu","Tuvalu","Tuvalu"],
    "UG": ["Uganda","Uganda","Uganda","Uganda"],
    "UA": ["Ukraine","Ucrania","Ukraine","Ucraina"],
    "AE": ["United Arab Emirates","Emiratos Árabes Unidos","Vereinigte Arabische Emirate","Emirati Arabi Uniti"],
    "GB": ["United Kingdom","Reino Unido","Vereinigtes Königreich","Regno Unito"],
    "US": ["United States","Estados Unidos","Vereinigte Staaten","Stati Uniti"],
    "UM": ["United States Minor Outlying Islands","Islas menores alejadas de los Estados Unidos","Minor Outlying Islands der Vereinigten Staaten","Isole minori esterne degli Stati Uniti"],
    "UY": ["Uruguay","Uruguay","Uruguay","Uruguay"],
    "UZ": ["Uzbekistan","Uzbekistán","Usbekistan","Uzbekistan"],
    "VU": ["Vanuatu","Vanuatu","Vanuatu","Vanuatu"],
    "VE": ["Venezuela","Venezuela","Venezuela","Venezuela"],
    "VN": ["Vietnam","Vietnam","Vietnam","Vietnam"],
    "VG": ["Virgin Islands, British","Islas Vírgenes Británicas","Britische Jungferninseln","Isole Vergini Britanniche"],
    "VI": ["Virgin Islands, U.S.","Islas Vírgenes, U.S.","Amerikanische Jungferninseln","Isole Vergini, Stati Uniti"],
    "WF": ["Wallis and Futuna","Wallis y Futuna","Wallis und Futuna","Wallis and Futuna"],
    "EH": ["Western Sahara","Sahara Occidental","Westsahara","Sahara occidentale"],
    "YE": ["Yemen","Yemen","Jemen","Yemen"],
    "ZM": ["Zambia","Zambia","Sambia","Zambia"],
    "ZW": ["Zimbabwe","Zimbabwe","Simbabwe","Zimbabwe"]
};

export default countries;
