const languages = [
    {value: "en", label: "English"},
    {value: "bg", label: "Български"},
    {value: "cz", label: "Čeština"},
    {value: "de", label: "Deutsch"},
    {value: "ee", label: "Eesti keel"},
    {value: "es", label: "Español"},
    {value: "fi", label: "Suomi"},
    {value: "fr", label: "Français"},
    {value: "gr", label: "ελληνικά"},
    {value: "hr", label: "Hrvatski"},
    {value: "hu", label: "Magyar"},
    {value: "il", label: "עברית"},
    {value: "it", label: "Italiano"},
    {value: "lv", label: "Latviešu valoda"},
    {value: "mk", label: "Македонски"},
    {value: "mt", label: "Malti"},
    {value: "pl", label: "Polski"},
    {value: "pt", label: "Português"},
    {value: "nl", label: "Nederlands"},
    {value: "ro", label: "Român"},
    {value: "ru", label: "Русский"},
    {value: "se", label: "Svenska"},
    {value: "si", label: "Slovenščina"},
    {value: "sk", label: "Slovenčina"},
    {value: "ua", label: "Українська"},
  ]
  export default languages;
