export const fields = {
  fields1: [
    {qid: 1, label: "In general, would you say life in America today is better, worse, or about the same as it was fifty years ago for people like you?", answers: [{anid: 1, label: "Better"}, {anid: 2, label: "Worse"}, {anid: 3, label: "About the same"}, {anid: 4, label: "Don't know"}]},
    {qid: 2, label: "Do you think the future of the next generation of Americans will be better, worse, or about the same as life today?", answers: [{anid: 5, label: "Better"}, {anid: 6, label: "Worse"}, {anid: 7, label: "About the same"}, {anid: 8, label: "Don't know"}]},
    {qid: 3, label: "In general, would you say life in America today is better, worse, or about the same as it was fifty years ago for people like you?", answers: [{anid: 9, label: "Better"}, {anid: 10, label: "Worse"}, {anid: 11, label: "About the same"}, {anid: 12, label: "Don't know"}]},
    {qid: 4, label: "Do you think the future of the next generation of Americans will be better, worse, or about the same as life today?", answers: [{anid: 13, label: "Better"}, {anid: 14, label: "Worse"}, {anid: 15, label: "About the same"}, {anid: 16, label: "Don't know"}]},
    {qid: 5, label: "Do you approve or disapprove of the way Donald Trump is handling his job as President?", answers: [{anid: 17, label: "Approve"}, {anid: 18, label: "Disapprove"}, {anid: 19, label: "Don't know"}]},
    {qid: 6, label: "All in all, are you satisfied or dissatisfied with the way things are going in this country today?", answers: [{anid: 20, label: "Satisfied"},{anid: 21, label: "Dissatisfied"},{anid: 22, label: "Don't know"}]},
    {qid: 7, label: "Which of these statements best describes you?", answers: [{anid: 23, label: "You are ABSOLUTELY CERTAIN that you are registered to vote at your current address"},{anid: 24, label: "You are PROBABLY registered, but there is a chance your registration has lapsed"},{anid: 25, label: "You are NOT registered to vote at your current address"}]},
    {qid: 8, label: "If the November mid-term elections were held today, how would you vote?", answers: [{anid: 26, label: "For the Democratic candidate in your district"},{anid: 27, label: "For the Republican candidate in your district"},{anid: 28, label: "For a mixture of Democratic and Republican candidates"},{anid: 29, label: "For other candidates"},{anid: 30, label: "Don't know"}]},
    {qid: 9, label: "Regardless of how you feel about your own representative, would you like to see most members of Congress re-elected in the next congressional election, or not?", answers: [{anid: 31, label: "Yes"}, {anid: 32, label: "No"}, {anid: 33, label: "Don't know"}]},
    {qid: 10, label: "Will the issue of which party controls Congress, the Republicans or the Democrats, be a factor in your vote for Congress this year, or not?", answers: [{anid: 34, label: "Yes, it will"}, {anid: 35, label: "No, it will not"}, {anid: 36, label: "Don't know"}]},
    {qid: 11, label: "Do you think of your vote for Congress as a vote FOR Donald Trump, as a vote AGAINST Donald Trump, or isn’t Donald Trump much of a factor in your vote?", answers: [{ anid: 37, label: 'A vote FOR Donald Trump' }, { anid: 38, label: 'A vote AGAINST Donald Trump' },{ anid: 39, label: 'Not a factor' }, { anid: 40, label: "Don't know" }]},
    {qid: 12, label: "Rate your chance of voting in November on a scale of one to ten. If ten represents you being certain to vote, where would you place yourself?", answers: [{ anid: 41, label: '1' }, { anid: 42, label: '2' },{ anid: 43, label: '3' },{ anid: 44, label: '4' }, { anid: 45, label: '5' },{ anid: 46, label: '6' }, { anid: 47, label: '7' }, { anid: 48, label: '8' },{ anid: 49, label: '9' },{ anid: 50, label: '10' },{ anid: 51, label: 'Rather not say' }]},
    {qid: 13, label: "In the 2016 presidential election between Donald Trump and Hillary Clinton, did things come up that kept you from voting, or did you happen to vote?", answers: [{anid: 52, label: "Voted"}, {anid: 53, label: "Did not vote (includes too young to vote)"}]},
    {qid: 14, label: "Did you vote for Trump, Clinton or someone else?", answers: [{anid: 54, label: "Trump"}, {anid: 55, label: "Clinton"}, {anid: 56, label: "Someone else"}]}],
  fields2: [
    {qid: 15, label: "How much do you personally like or dislike the Republic Party and its supporters?", answers: [{anid: 57, label: "Don't know"}, {anid: 58, label: "Strongly dislike"}, {anid: 59, label: ""},{anid: 60, label: ""},{anid: 61, label: ""},{anid: 62, label: ""},{anid: 63, label: ""},{anid: 64, label: ""},{anid: 65, label: ""},{anid: 66, label: ""}, {anid: 67, label: "Strongly like"}]},
    {qid: 16, label: "How much do you personally like or dislike the Democratic Party and its supporters?", answers: [{anid: 68, label: "Don't know"}, {anid: 69, label: "Strongly dislike"}, {anid: 70, label: ""},{anid: 71, label: ""},{anid: 72, label: ""},{anid: 73, label: ""},{anid: 74, label: ""},{anid: 75, label: ""},{anid: 76, label: ""},{anid: 77, label: ""}, {anid: 78, label: "Strongly like"}]}
  ],
  fields3: [
    {qid: 17, label: "Would you say that Republicans are more ____ than other Americans?", answers: [ { anid: 79, label: 'Closed-minded' }, { anid: 80, label: 'Open-minded' },{ anid: 81, label: 'Immoral' },{ anid: 82, label: 'Moral' },{ anid: 83, label: 'Dishonest' },{ anid: 84, label: 'Honest' },{ anid: 85, label: 'Unintelligent' },{ anid: 86, label: 'Intelligent' } ]},
    {qid: 18, label: "Would you say that Democrats are more ____ than other Americans?", answers: [ { anid: 187, label: 'Closed-minded' }, { anid: 87, label: 'Open-minded' },{ anid: 88, label: 'Immoral' },{ anid: 89, label: 'Moral' },{ anid: 90, label: 'Dishonest' },{ anid: 91, label: 'Honest' },{ anid: 92, label: 'Unintelligent' },{ anid: 93, label: 'Intelligent' } ]},
    {qid: 19, label: "How would you feel if you had a son or daughter who married a Republican supporter?", answers: [ { anid: 94, label: 'Very unhappy' }, { anid: 95, label: 'Somewhat unhappy' },{ anid: 96, label: 'Neither happy nor unhappy' },{ anid: 97, label: 'Somewhat happy' },{ anid: 98, label: 'Very happy' }, { anid: 99, label: "Don't know" } ]},
    {qid: 20, label: "How would you feel if you had a son or daughter who married a Democrat supporter?", answers: [ { anid: 100, label: 'Very unhappy' }, { anid: 101, label: 'Somewhat unhappy' },{ anid: 102, label: 'Neither happy nor unhappy' },{ anid: 103, label: 'Somewhat happy' },{ anid: 104, label: 'Very happy' }, { anid: 105, label: "Don't know" } ]},
  ],
fields4: [
  {qid: 21, label: "Are you male or female?", answers: [{anid: 106, label: "Male"}, {anid: 107, label: "Female"}]},
  {qid: 22, label: "Which of these best describes you?", answers: [ { anid: 108, label: 'Married' },
    { anid: 109, label: 'Living with a partner' },
    { anid: 110, label: 'Divorced' },
    { anid: 111, label: 'Separated' },
    { anid: 112, label: 'Widowed' },
    { anid: 113, label: 'Never been married' } ]},
  {qid: 23, label: "How many people, including yourself, live in your household? Include all adults and children who think of your household as their primary place of residence.", answers: [ { anid: 114, label: '1' },
  { anid: 115, label: '2' },
  { anid: 116, label: '3' },
  { anid: 117, label: '4' },
  { anid: 118, label: '5' },
  { anid: 119, label: '6' },
  { anid: 120, label: '7' },
  { anid: 121, label: '8' },
  { anid: 122, label: '9' },
  { anid: 123, label: '10' },
  { anid: 124, label: '>10' },
  { anid: 125, label: "Don't know" },
  { anid: 126, label: 'Rather not say' } ]},
  {qid: 24, label: "What is the highest level of school you have completed or the highest degree you have received?", answers: [ { anid: 127,
    label: 'Less than high school (Grades 1-8 or no formal schooling)' },
    { anid: 128,
      label: 'High school incomplete (Grades 9-11 or Grade 12 with NO diploma)' },
    { anid: 129,
      label: 'High school graduate (Grade 12 with diploma or GED certificate)' },
    { anid: 130,
      label: 'Some college, no degree (includes some community college)' },
    { anid: 131,
      label: 'Two year associate degree from a college or university' },
    { anid: 132,
      label: 'Four year college or university degree/Bachelor’s degree  (e.g., BS, BA, AB)' },
    { anid: 133,
      label: 'Some postgraduate or professional schooling, no postgraduate degree (e.g. some graduate school)' },
    { anid: 134,
      label: 'Postgraduate or professional degree, including master’s, doctorate, medical or law degree (e.g., MA, MS, PhD, MD, JD, graduate school)' },
    { anid: 135, label: "Don't know" },
    { anid: 136, label: 'Rather not say' } ]},
  {qid: 25, label: "Which of the following describes your race?", answers: [ { anid: 137,
    label: 'White (e.g., Caucasian, European, Irish, Italian, Arab, Middle Eastern)' },
    { anid: 138,
      label: 'Black or African-American (e.g., Negro, Kenyan, Nigerian, Haitian)' },
    { anid: 139,
      label: 'Asian or Asian-American (e.g., Asian Indian, Chinese, Filipino, Vietnamese or other Asian origin groups)' },
    { anid: 140,
      label: 'Native American/American Indian/Alaska Native' },
    { anid: 141, label: 'Hispanic/Latino' },
    { anid: 142, label: 'Don’t know' },
    { anid: 143, label: 'Rather not say' } ]},
  {qid: 26, label: "What is your present religion, if any?", answers: [ { anid: 144,
    label: 'Protestant (Baptist, Methodist, Non-denominational, Lutheran, Presbyterian, Pentecostal, Episcopalian, Reformed, Church of Christ, Jehovah’s Witness, etc.)' },
    { anid: 145, label: 'Roman Catholic (Catholic)' },
    { anid: 146,
      label: 'Mormon (Church of Jesus Christ of Latter-day Saints/LDS)' },
    { anid: 147,
      label: 'Orthodox (Greek, Russian, or some other orthodox church)' },
    { anid: 148, label: 'Jewish (Judaism)' },
    { anid: 149, label: 'Muslim (Islam)' },
    { anid: 150, label: 'Buddhist' },
    { anid: 151, label: 'Hindu' },
    { anid: 152, label: 'Atheist (do not believe in God)' },
    { anid: 153, label: 'Agnostic (not sure if there is a God)' },
    { anid: 154, label: 'Another (not listed)' },
    { anid: 155, label: "Don't know" },
    { anid: 156, label: 'Rather not say' },
    { anid: 157, label: 'Other' } ]},
  {qid: 27, label: "Last year, in 2017, what was your total family income, before taxes?", answers: [ { anid: 158, label: 'Less than $10,000' },
    { anid: 159, label: '10 to under $20,000' },
    { anid: 160, label: '20 to under $30,000' },
    { anid: 161, label: '30 to under $40,000' },
    { anid: 162, label: '40 to under $50,000' },
    { anid: 163, label: '50 to under $75,000' },
    { anid: 164, label: '75 to under $100,000' },
    { anid: 165, label: '100 to under $150,000' },
    { anid: 166, label: '$150,000 or more' },
    { anid: 167, label: "Don't know" },
    { anid: 168, label: 'Rather not say' } ]},
  {qid: 28, label: "In politics today, do you consider yourself a Republican, Democrat, or independent?", answers: [ { anid: 169, label: 'Republican' },
    { anid: 170, label: 'Democrat' },
    { anid: 171, label: 'Independent' },
    { anid: 172, label: 'No preference' },
    { anid: 173, label: 'Other party' },
    { anid: 174, label: "Don't know" } ]},
],
fields5: [
  {qid: 29, label: "How often, if ever, do you notice advertisements when on Facebook?", answers: [ { anid: 175, label: 'Often' },
    { anid: 176, label: 'Sometimes' },
    { anid: 177, label: 'Hardly ever' },
    { anid: 178, label: 'Never' } ]},
  {qid: 30, label: "How often, if ever, do you touch or click on ads when on Facebook?", answers: [ { anid: 179, label: 'Often' },
    { anid: 180, label: 'Sometimes' },
    { anid: 181, label: 'Hardly ever' },
    { anid: 182, label: 'Never' } ]},
  {qid: 31, label: "Thinking about news (by news we mean information about events and issues that involve more than just your friends and family), how often do you get news from social media?", answers: [ { anid: 183, label: 'Often' },
    { anid: 184, label: 'Sometimes' },
    { anid: 185, label: 'Hardly ever' },
    { anid: 186, label: 'Never' } ]},
]}
