import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  en: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Loading, thank you for your patience',
    register: {
      welcome1: 'Who Targets Me helps people understand how targeted social',
      welcome2: 'media advertising is used to persuade them.',
      welcome3: 'helps us to show you the right version of Who Targets Me',
      welcome4: 'so we know your next election and voting system',
      select_language: 'Select your language',
      terms: '<span>By continuing you agree to the <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'I Agree',
      back: 'Back',
      next: 'Next',
      country: 'Country',
      enter_country: 'Select your country',
      postcode: 'Postcode / Zipcode',
      enter_postcode: 'Please enter your postcode or zipcode',
      postcode_error: 'It looks like you entered an invalid postcode',
      gender: 'Your gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      years_of_age: 'How old are you (in years)?',
      age: 'Age',
      confirming: 'Confirming your details',
      request_error: 'The server responded with the following message:',
      unknown_error: 'Unknown error, if this persists please get in touch!',
      share: 'Share the project to help your friends learn more about the targeted political ads they see.',
      share1: 'Share the project',
      share2: ' to help your friends learn more about the targeted political ads they see.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Skip',
      shareFacebook: '@WhoTargetsMe is investigating dark advertising, find out who targets you https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe is investigating dark advertising, find out who targets you https://whotargets.me/',
      political_affiliation: 'Your political views',
      political_affiliation_description: 'Most people think of politics as having a \'left\' and a \'right\'. How would you describe your own views?',
      us_labels: ['No affiliation', 'Very liberal', 'Moderately liberal', 'Slightly liberal', 'Center', 'Slightly conservative', 'Moderately conservative', 'Very conservative'],
      non_us_labels: ['No affiliation', 'Very left wing', 'Moderately left wing', 'Slightly left wing', 'Center', 'Slightly right wing', 'Moderately right wing', 'Very right wing'],
      would_rather_not_say: 'Would rather not say',
      county: 'County',
    },
    results: {
      my_constituency: 'My Constituency',
      constituency_size: 'You are one of %i volunteers in %s, can you help us reach %i?',
      constituency_size_one: 'You are the first volunteer in %s!. Can you help us find more?',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Website',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'T&Cs',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy Policy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  de: {
    who_targets_me: 'Wer bezahlt für meine Stimme?',
    loading: 'Daten werden geladen, vielen Dank für deine Geduld',
    register: {
      select_language: 'Bitte wählen Sie Ihre bevorzugte Sprache aus',
      terms: '<span>By continuing you agree to the <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'Ich stimme zu',
      back: 'Zurück',
      next: 'Nächster',
      country: 'Land',
      enter_country: 'Bitte geben Sie Ihr Land an',
      postcode: 'Postleitzahl',
      enter_postcode: 'Bitte geben Sie Ihre Postleitzahl ein',
      postcode_error: 'Es sieht so aus, als hätten Sie eine ungültige Postleitzahl eingegeben',
      gender: 'Dein Geschlecht',
      male: 'Männlich',
      female: 'Weiblich',
      other: 'Andere',
      years_of_age: 'Wie alt bist du (in Jahren)?',
      age: 'Alter',
      confirming: 'Bestätigen Sie Ihre Angaben',
      request_error: 'Der Server antwortete mit folgendem Fehler:',
      unknown_error: 'Unbekannter Fehler, falls anhalten Sie bitte in Kontakt!',
      share: 'Share Who Targets Me mit Ihren Freunden, um digitale Transparenz zu unterstützen',
      share1: 'Share the project',
      share2: ' to help your friends learn more about the targeted political ads they see.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Überspringen',
      shareFacebook: '@WhoTargetsMe enthullt Dark Ads an der #BTW17 Finde heraus, welche Parteien auf dich zielen https://whotargets.me/de',
      shareTwitter: '@WhoTargetsMe enthullt Dark Ads an der #BTW17 Finde heraus, welche Parteien auf dich zielen https://whotargets.me/de',
      political_affiliation: 'Please choose your political affiliation',
    },
    results: {
      my_constituency: 'Mein Bundestagswahlkreis',
      constituency_size: 'Du bist einer von %i Freiwilligen in %s, kannst du uns helfen %i zu erreichen?',
      constituency_size_one: 'Glückwünsch! Du bist der/die erste/r Freiwillige in %s. Kannst du uns helfen, noch mehr zu finden?',
      no_results_explanation: 'Who Targets Me arbeitet im Hintergrund, um zu ermitteln, welche Werbung du siehst. Diese Seite wird mit Statistiken aktualisiert, sobald wir genug Daten gesammelt haben.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Webseite',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Bedingungen',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privatsphäre',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  es: {
    who_targets_me: '¿De quién soy el blanco?',
    loading: 'Cargando, gracias por su paciencia',
    register: {
      select_language: 'Por favor seleccione su idioma',
      terms: '<span>Al continuar usted acepta las <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'Acepto',
      back: 'Volver',
      next: 'Siguiente',
      country: 'País',
      enter_country: 'Por favor ingrese su país de residencia',
      postcode: 'Tu género',
      enter_postcode: 'Por favor ingrese su código postal',
      postcode_error: 'Parece que ingresaste un código postal no válido.',
      gender: 'Tu género',
      male: 'Hombre',
      female: 'Mujer',
      other: 'Otro',
      years_of_age: '¿Qué edad tiene usted (en años)?',
      age: 'Edad',
      confirming: 'Confirmando sus datos de registro',
      request_error: 'El servidor a respondido con el siguiente mensaje:',
      unknown_error: 'Error desconocido, ¡Si persiste por favor contáctenos!',
      share: 'Comparte ¿De quién soy el blanco? con tus amigos para apoyar la transparencia digital',
      shareOnFacebook: 'Compartir en Facebook',
      shareOnTwitter: 'Compartir en Twitter',
      skip: 'Saltar',
      shareFacebook: '@WhoTargetsMe esta investigando publicidad oculta, averigua de quien eres blanco https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe esta investigando publicidad oculta, averigua de quien eres blanco https://whotargets.me/',
    },
    results: {
      my_constituency: 'Mi circunscripción',
      constituency_size: 'Eres uno de %i voluntario de %s, ¿Puedes ayudarnos a alcanzar %i?',
      constituency_size_one: 'Eres el primer voluntario de %s!. ¿Puedes ayudarnos a averiguar más?',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Página Web',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Terminos',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacidad',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  it: {
    who_targets_me: 'Who Targets Me?',
    loading: 'In caricamento, grazie per la pazienza',
    register: {
      select_language: 'Seleziona la tua lingua preferita',
      terms: '<span>Procedendo con la registrazione accetti <a href="https://whotargets.me/en/terms/">i termini di utilizzo</a> e <a href="https://whotargets.me/en/privacy-policy/">la privacy policy</a></span>',
      agree: 'Accetto',
      back: 'Indietro',
      next: 'Prossimo',
      country: 'Paese',
      enter_country: 'Inserisci il tuo Paese di residenza',
      postcode: 'CAP',
      enter_postcode: 'Inserisci il tuo CAP',
      postcode_error: 'Il CAP inserito non sembra essere valido',
      gender: 'Il tuo genere',
      male: 'Uomo',
      female: 'Donna',
      other: 'Altro',
      years_of_age: 'Quanti anni hai?',
      age: 'Età',
      confirming: 'Conferma i dettagli inseriti',
      request_error: 'Il server ha restituito il seguente messaggio:',
      unknown_error: 'Errore sconosciuto, se dovesse accadere di nuovo non esitare a contattarci!',
      share: 'Condividi Who Targets Me con i tuoi amici per supportare la trasparenza digitale',
      shareOnFacebook: 'Condividi su Facebook',
      shareOnTwitter: 'Condividi su Twitter',
      skip: 'Salta',
      shareFacebook: '@WhoTargetsMe svela chi sta utilizzando campagne pubblicitarie politiche oscure. Scopri chi ti sta prendendo di mira https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe svela chi sta utilizzando campagne pubblicitarie politiche oscure. Scopri chi ti sta prendendo di mira https://whotargets.me/',
    },
    results: {
      my_constituency: 'La mia circoscrizione',
      constituency_size: 'Sei uno dei %i volontari nella tua circoscrizione (%s), puoi aiutarci a raggiungerne %i?',
      constituency_size_one: 'Tu sei il primo volontario in %s!. Puoi aiutarci a trovarne altri?',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Sito web',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Termini di utilizzo',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  hu: {
    who_targets_me: 'Célkeresztben',
    loading: 'Az oldal töltődik, kis türelmet kérünk',
    register: {
      select_language: 'Válasszon nyelvet',
      terms: '<span>A folytatással elfogadja a <a href="https://whotargets.me/en/terms/">felhasználási feltételeket</a> és <a href="https://whotargets.me/en/privacy-policy/">az adatkezelési irányelveket</a></span>',
      agree: 'Elfogadom',
      back: 'Vissza',
      next: 'Tovább',
      country: 'Ország',
      enter_country: 'Tartózkodási ország',
      postcode: 'Irányítószám',
      enter_postcode: 'Adja meg az irányítószámát',
      postcode_error: 'Az irányítószám formátuma nem megfelelő',
      gender: 'Nemed',
      male: 'Férfi',
      female: 'Nő',
      other: 'Egyéb',
      years_of_age: 'Hány éves?',
      age: 'Kor',
      confirming: 'Adataim megerősítése',
      request_error: 'A szerver a következő üzenettel tért vissza:',
      unknown_error: 'Ismeretlen hiba, ha továbbra is ezt tapasztalja, lépjen velünk kapcsolatba!',
      share: 'Segítsen növelni a digitális átláthatóságot! Ossza meg a Célkeresztben alkalmazást az ismerőseivel.',
      shareOnFacebook: 'Megosztom a Facebookon',
      shareOnTwitter: 'Megosztom a Twitteren',
      skip: 'Ezt most kihagyom',
      shareFacebook: 'A @WhoTargetsMe az online hirdetések sötét oldalát vizsgálja. Nézze meg, Önnek ki üzen. https://whotargets.me/',
      shareTwitter: 'A @WhoTargetsMe az online hirdetések sötét oldalát vizsgálja. Nézze meg, Önnek ki üzen. https://whotargets.me/',
      political_affiliation: 'Melyik politikai oldal áll Önhöz a legközelebb?',
      political_affiliation_description: 'A legtöbben jobb- és baloldalról beszélnek a politikában. Ön hogyan írná le a nézeteit?',
      us_labels: ['No affiliation', 'Erőteljesen baloldali', 'Mérsékelten baloldali', 'Kissé baloldali', 'Centrista', 'Kissé jobboldali', 'Mérsékelten jobboldali', 'Erőteljesen jobboldali'],
      non_us_labels: ['No affiliation', 'Erőteljesen baloldali', 'Mérsékelten baloldali', 'Kissé baloldali', 'Centrista', 'Kissé jobboldali', 'Mérsékelten jobboldali', 'Erőteljesen jobboldali'],
      would_rather_not_say: 'Nem akarok mondani',
    },
    results: {
      my_constituency: 'Választókörzetem',
      constituency_size: '%s körzetben %i önkéntesünk van, segítsen nekünk elérni, hogy ennyi legyen: %i!',
      constituency_size_one: 'Ön az első önkéntes itt: %s. Hívjon meg másokat is!',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Honlap',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Felhasználási feltételek',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Adatvédelem',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  ru: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Загрузка, спасибо за ваше терпение',
    register: {
      welcome1: 'Who Targets Me исследует скрытую рекламу,',
      welcome2: 'узнайте, кто нацелен на вас.',
      welcome3: 'Помогает показать вам правильную версию Who Targets Me.',
      welcome4: 'Чтобы мы знали, когда у вас будут следующие выборы.',
      select_language: 'Выберите нужный язык',
      terms: '<span>Продолжая, вы соглашаетесь с <a href="https://whotargets.me/en/terms/">условия и положения</a> и <a href="https://whotargets.me/en/privacy-policy/">политика конфиденциальности</a></span>',
      agree: 'Согласен',
      back: 'Назад',
      next: 'Вперед',
      country: 'Страна',
      enter_country: 'Выберите страну проживания',
      postcode: 'Почтовый индекс',
      enter_postcode: 'Укажите почтовый индекс',
      postcode_error: 'Похоже, вы ввели неверный почтовый индекс',
      gender: 'Ваш пол',
      male: 'Мужской',
      female: 'Женский',
      other: 'Другой',
      years_of_age: 'Сколько вам лет?',
      age: 'Возраст',
      confirming: 'Подтвердить данные',
      request_error: 'Сервер ответил следующим сообщением:',
      unknown_error: 'Неизвестная ошибка, если это повторится, пожалуйста, свяжитесь с нами!',
      share: 'Поделитесь проектом, чтобы помочь вашим друзьям узнать больше о политической рекламе, которую они видят.',
      share1: 'Поделиться проектом',
      share2: ' чтобы помочь вашим друзьям узнать больше о политической рекламе, которую они видят.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Пропустить',
      shareFacebook: '@WhoTargetsMe исследует скрытую рекламу, узнайте, кто нацелен на вас https://whotargets.me/',
      shareTwitter: "@WhoTargetsMe исследует скрытую рекламу, узнайте, кто нацелен на вас https://whotargets.me/",
      political_affiliation: 'Ваши политические взгляды',
      political_affiliation_description: 'Большинство людей думает о политике, как о делении на  \'левых\' и \'правых\'. Как бы вы описали свои собственные взгляды?',
      us_labels: ['Нет принадлежности', 'Ультралиберальные', 'Умеренно либеральные', 'Слегка либеральные', 'Центристские', 'Слегка консервативные', 'Умеренно консервативные', 'Ультраконсервативные'],
      non_us_labels: ['Нет принадлежности', 'Ультралевые', 'Умеренно левые', 'Левоцентристские', 'Центристские', 'Правоцентристские', "Умеренно правые", "Ультраправые"],
      would_rather_not_say: "Предпочитаю не говорить",
      county: "Округ",
    },
    results: {
      my_constituency: 'Мои избиратели',
      constituency_size: 'Вы один из % добровольцев в %, можете ли вы помочь нам достичь %?',
      constituency_size_one: 'Вы первый волонтер из %!. Можете ли вы помочь нам найти больше?',
      no_results_explanation: 'Результаты появятся здесь, когда у нас будет достаточно данных. Продолжайте использовать Facebook в обычном режиме и возвращайтесь через несколько дней.',
      no_country_explanation1: "Мы предоставим персонализированные результаты",
      no_country_explanation2: " скоро. А пока продолжайте использовать Facebook в обычном режиме, и спасибо, что приняли участие в Who Targets Me.",
      delete_request: "Если вы удалите данные, то они будут недоступны для исследования. У вас есть три варианта:",
      data_deleted: "Ваши данные были удалены и новые данные не собираются.",
      data_deleted2: "Теперь вы можете удалить приложение, щелкнув правой кнопкой мыши по значку 'Who Targets Me' на панели инструментов браузера, и выбрать 'Удалить ...'.",
      data_deleted3: "Еще раз спасибо за участие. Вы можете продолжать следить за обновлениями проекта через Twitter, Facebook и рассылку электронной почты.",
      delete_data: "Удалить данные",
      delete_data_message: "Удалить все данные, которые были собраны с помощью Who Targets Me вместе с вашим анонимным профилем.",
      remove_WTM: "Удалить WTM",
      remove_WTM_message: "Щелкните правой кнопкой мыши по значку приложения и выберите 'Удалить ...'",
      remove_WTM_message2: "Сохранить ваши данные и анонимный профиль для исследований.",
      cancel: "Отменить",
      cancel_message: "Вернуться к предыдущему экрану и продолжить использовать Who Targets Me",
      uninstall: "Чтобы удалить, щелкните правой кнопкой мыши по значку расширения на панели инструментов.",
      shareFacebook1: "Я был мишенью для ",
      shareFacebook2: "Установите Who Targets Me, чтобы узнать, кто использует политическую рекламу в социальных сетях, чтобы получить ваш голос. https://whotargets.me",
      shareTwitter1: "Я был мишенью для ",
      shareTwitter2: ". Установите Who Targets Me, чтобы узнать, кто использует политическую рекламу в социальных сетях, чтобы получить ваш голос. https://whotargets.me",
      results_screen1: "К вам пытается обратиться партия ", // You are being targeted by {party name}.
      results_screen2: "В общей сложности вы видели ", // In total you've seen {quantity} political ads
      results_screen3: " политических рекламных объявлений, из которых ", //of which.
      results_screen4: " были от ", //{quantity} were from {party name}.
    },
    links: {
      website: {
        title: 'Веб-сайт',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Условия',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Конфиденциальность',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  lv: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Notiek ielāde, paldies par pacietību',
    register: {
      welcome1: 'Who Targets Me platforma palīdz saprast, kā sociālo mediju reklāma',
      welcome2: 'tiek izmantota, lai jūs ietekmētu.',
      welcome3: 'Palīdzi mums parādīt pareizo Who Targets Me versiju.',
      welcome4: 'Lai mēs zinātu, kad jums ir nākamās vēlēšanas.',
      select_language: 'Lūdzu, izvēlieties vēlamo valodu',
      terms: '<span>Turpinot jūs piekrītat <a href="https://whotargets.me/en/terms/">lietošanas noteikumiem</a> un <a href="https://whotargets.me/en/privacy-policy/">konfidencialitātes politikai</a></span>',
      agree: 'Piekrītu',
      back: 'Atpakaļ',
      next: 'Tālāk',
      country: 'Valsts',
      enter_country: 'Lūdzu, ievadiet savu valsti',
      postcode: 'Pasta indekss',
      enter_postcode: 'Lūdzu ievadiet savu pasta indeksu',
      postcode_error: 'Izskatās, ka ievadījāt nederīgu pasta indeksu',
      gender: 'Es esmu...',
      male: 'vīrietis',
      female: 'sieviete',
      other: 'cits',
      years_of_age: 'Cik jums ir gadu?',
      age: 'Vecums',
      confirming: 'Apstiprinām jūsu datus',
      request_error: 'Serveris atbildēja ar šādu ziņojumu:',
      unknown_error: 'Nezināma kļūda. Ja tā atkārtojas, lūdzu, sazinieties ar mums!',
      share: 'Pastāstiet par Who Targets Me saviem draugiem un atbalstiet mūsu darbu',
      share1: 'Dalies ar projektu',
      share2: ' Pastāsti par mums saviem draugiem, lai arī viņi varētu zināt vairāk par mērķētām politiskajām reklāmām.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Izlaist',
      shareFacebook: '@WhoTargetsMe pēta tiešsaistes reklāmu tumšo tirgu - uzzini, kas ir mērķēts uz tevi https://whotargets.me/',
      shareTwitter: "@WhoTargetsMe pēta tiešsaistes reklāmu tumšo tirgu - uzzini, kas ir mērķēts uz tevi https://whotargets.me/",
      political_affiliation: 'Jūsu politiskā nostāja',
      political_affiliation_description: 'Lielākā daļa cilvēku politiskos uzskatus iedala  \'labējos\' un \'kreisajos\'. Kā jūs raksturotu savus uzskatus?',
      us_labels: ['Nav politiskās piederības', 'Ļoti liberāli uzskati', 'Liberāli uzskati', 'Daļēji liberāli uzskati', 'Centriski uzskati', 'Daļēji konservatīvi uzskati', 'Konservatīvi uzskati', 'Ļoti konservatīvi uzskati'],
      non_us_labels: ['Nav politiskās piederības', 'Izteikti labēji uzskati', 'Labēji uzskati', 'Daļēji labēji uzskati', 'Centriski uzskati', 'Daļēji kreisi uzskati', 'Kreisi uzskati', 'Ļoti kreisi uzskati'],
      would_rather_not_say: "Nevēlos uz šo jautājumu atbildēt",
      county: "Valsts",
    },
    results: {
      my_constituency: 'Mans vēlēšanu apgabals',
      constituency_size: 'Tu esi viens no %i brīvprātīgajiem %s, vai vari palīdzēt mums sasniegt %i?',
      constituency_size_one: 'Tu esi pirmais brīvprātīgais no %s! Vai vari mums palīdzēt atrast vairāk brīvprātīgo?',
      no_results_explanation: 'Who Targets Me darbojas fonā, lai noteiktu, kādas reklāmas jūs redzat. Šī lapa tiks atjaunināta ar statistiku, tiklīdz būsim savākuši pietiekami daudz datu.',
      no_country_explanation1: "Mēs jums sniegsim personalizētus rezultātus ",
      no_country_explanation2: " drīzumā. Tikmēr turpiniet izmantot Facebook kā ierasts, un liels paldies par Jūsu dalību Who Targets Me projektā.",
      delete_request: "Izdzēšot visu informāciju, tā vairs nebūs pieejama pētījumam. Jums ir trīs izvēles iespējas:",
      data_deleted: "Visa Jūsu savāktā informācija tiek izdzēsta un jauna informācija netiek iegūta",
      data_deleted2: "Jūs varat atvienot spraudni uzklikšķinot uz Who Targets Me ikonas jūsu interneta pārlūka rīkjoslā, un izvēloties  'Remove...'",
      data_deleted3: "Paldies Jums par dalību mūsu projektā. Jūs varat turpināt sekot līdzi mūsu darbībai Twitter, Facebook, kā arī pieteikties informatīvajiem epastiem.",
      delete_data: "Dzēst datus",
      delete_data_message: "Dzēš visu informāciju, ko esat ieguvis izmantojot Who Targets Me, ieskaitot Jūsu anonīmo progilu.",
      remove_WTM: "Noņemt WTM",
      remove_WTM_message: "Labais klikšķis uz aplikācijas ikonas un tad izvēlaties'Remove...'",
      remove_WTM_message2: "Saglabā jūsu datus un anonīmo profilu pētījumam.",
      cancel: "Atcelt",
      cancel_message: "Doties atpakaļ uz iepriekšējo lapu un turpināt izmnantot Who Targets Me",
      uninstall: "Lai atinstalētu, ar labo peles pogu klikšķiniet uz aplikācijas ikonas jūsu rīkjoslā.",
      shareFacebook1: "Kā mērķauditoriju mani izvēlas: ",
      shareFacebook2: ". Instalē Who Targets Me, lai noskaidrotu kuru politisko spēku sociālo tīklu reklāmas tiek izmantotas, lai iegūtu Tavu balsi. https://whotargets.me",
      shareTwitter1: "Kā mērķauditoriju mani izvēlas ",
      shareTwitter2: ". Instalē Who Targets Me, lai noskaidrotu kuru politisko spēku sociālo tīklu reklāmas tiek izmantotas, lai iegūtu Tavu balsi. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Mājaslapa',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Noteikumi',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Konfidencialitāte',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  pt: {
    who_targets_me: 'Você na mira',
    loading: 'Carregando, obrigado por esperar',
    register: {
      welcome1: 'Who Targets Me helps people understand how targeted social',
      welcome2: 'media advertising is used to persuade them.',
      welcome3: 'helps us to show you the right version of Who Targets Me',
      welcome4: 'so we know your next election and voting system',
      select_language: 'Por favor, selecione seu idioma preferido',
      terms: '<span>Ao continuar, você estará concordando com os <a href="https://whotargets.me/en/terms/">termos de uso</a> e <a href="https://whotargets.me/en/privacy-policy/">Política de Privacidade</a></span>',
      agree: 'Eu concordo',
      back: 'Voltar',
      next: 'Avançar',
      country: 'País',
      enter_country: 'Por favor, digite seu país de residência',
      postcode: 'CEP',
      enter_postcode: 'Por favor, digite seu CEP',
      postcode_error: 'Você digitou um CEP inválido',
      gender: 'Seu gênero',
      male: 'masculino',
      female: 'feminino',
      other: 'outro',
      years_of_age: 'Qual a sua idade?',
      age: 'Idade',
      confirming: 'Confirme suas informações',
      request_error: 'O servidor respondeu com a seguinte mensagem:',
      unknown_error: 'Erro desconhecido. Se persistir, por favor, entre em contato!',
      share: 'Compartilhe esse projeto para ajudar seus amigos a aprender mais sobre marketing político direcionado.',
      share1: 'Compartilhe o projeto',
      share2: ' para ajudar seus amigos a aprender mais sobre marketing político direcionado.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Pular',
      shareFacebook: '@WhoTargetsMe e @internetlabbr estão investigando propaganda eleitoral no Facebook, descubra de quem você está na mira https://whotargets.me',
      shareTwitter: '@WhoTargetsMe e @internetlabbr estão investigando propaganda eleitoral no Facebook, descubra de quem você está na mira https://whotargets.me',
      political_affiliation: 'Suas posições políticas',
      political_affiliation_description: 'A maioria das pessoas pensam em política em termos de \'esquerda (progressista)\' e \'direita (conservadora)\'. Nestes termos como você descreveria sua posição?',
      us_labels: ['Sem afiliação', 'Muito liberal', 'Liberal moderado', 'Pouco liberal', 'Centro', 'Pouco conservador', 'Conservador moderado', 'Muito conservador'],
      non_us_labels: ['Sem afiliação', 'Extrema esquerda', 'Esquerda', 'Centro-esquerda', 'Centro', 'Centro-direita', 'Direita', 'Extrema direita'],
      would_rather_not_say: 'Prefiro não dizer',
      county: 'Estado',
    },
    results: {
      my_constituency: 'Meu domicílio eleitoral',
      constituency_size: 'Você é um dos %i voluntários em %s, você poderia nos ajudar a chegar a %i?',
      constituency_size_one: 'Você é o primeiro voluntário em %s!. Você poderia nos ajudar a encontrar outros?',
      no_results_explanation: 'Os resultados serão mostrados aqui quando nós coletarmos dados suficientes. Continue usando o Facebook e verifique novamente em alguns dias.',
      no_country_explanation1: "Nós iremos trazer resultados personalizados para ",
      no_country_explanation2: " em breve. Enquanto isso, continue usando o Facebook e obrigado por participar do Você Na Mira.",
      delete_request: "Deletar seus dados os torna indisponíveis para pesquisa. Você tem três opções:",
      data_deleted: "Seus dados foram deletados e nenhum novo dado será coletado.",
      data_deleted2: "Você pode remover a extensão clicando com o botão direito no ícone do Você Na Mira no seu navegador, e selecionando 'Remover do Chrome'",
      data_deleted3: "Obrigado por participar. Você pode continuar acompanhando atualizações do projeto pelo Twitter e pelo Facebook.",
      delete_data: "Deletar dados",
      delete_data_message: "Deletar todos os dados coletados pelo Você Na Mira junto com seu perfil anônimo.",
      remove_WTM: "Remover Você Na Mira",
      remove_WTM_message: "Clique no ícone da extensão e selecione 'Remover do Chrome'",
      remove_WTM_message2: "Preservar seus dados e perfil anônimo para pesquisa.",
      cancel: "Cancelar",
      cancel_message: "Voltar para a tela anterior e continuar usando Você Na Mira",
      uninstall: "Para desinstalar, clique com o botão direito no ícone da extensão na barra de ferramentas do seu navegador",
      shareFacebook1: "Eu estou na mira de ",
      shareFacebook2: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://whotargets.me",
      shareTwitter1: "Eu estou na mira de ",
      shareTwitter2: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://whotargets.me",
      shareFacebook2BR: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://vocenamira.org.br",
      shareTwitter2BR: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://vocenamira.org.br",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Site',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Termos de uso',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Política de privacidade',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
});

export const changeLocale = (locale) => {
  chrome.storage.promise.local.set({language: locale});
  strings.setLanguage(locale);
}

chrome.storage.promise.local.get('language')
  .then((result) => {
    strings.setLanguage(result.language);
  })
  .catch(() => {
    chrome.storage.promise.local.set({language: 'en'});
    strings.setLanguage('en');
  })

export default strings;
