import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  en: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Loading, thank you for your patience',
    register: {
      welcome1: 'Who Targets Me helps people understand how targeted social',
      welcome2: 'media advertising is used to persuade them.',
      welcome3: 'helps us to show you the right version of Who Targets Me',
      welcome4: 'so we know your next election and voting system',
      select_language: 'Select your language',
      terms: '<span>By continuing you agree to the <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'I Agree',
      back: 'Back',
      next: 'Next',
      country: 'Country',
      enter_country: 'Select your country',
      postcode: 'Postcode / Zipcode',
      enter_postcode: 'Please enter your postcode or zipcode',
      postcode_error: 'It looks like you entered an invalid postcode',
      gender: 'Your gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      years_of_age: 'How old are you (in years)?',
      age: 'Age',
      confirming: 'Confirming your details',
      request_error: 'The server responded with the following message:',
      unknown_error: 'Unknown error, if this persists please get in touch!',
      share: 'Share the project to help your friends learn more about the targeted political ads they see.',
      share1: 'Share your results',
      share2: ' to help people learn about targeted political ads.',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Skip',
      shareFacebook: '@WhoTargetsMe is investigating dark advertising, find out who targets you https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe is investigating dark advertising, find out who targets you https://whotargets.me/',
      political_affiliation: 'Your political views',
      political_affiliation_description: 'Most people think of politics as having a \'left\' and a \'right\'. How would you describe your own views?',
      us_labels: ['No affiliation', 'Very liberal', 'Moderately liberal', 'Slightly liberal', 'Center', 'Slightly conservative', 'Moderately conservative', 'Very conservative'],
      non_us_labels: ['No affiliation', 'Very left wing', 'Moderately left wing', 'Slightly left wing', 'Center', 'Slightly right wing', 'Moderately right wing', 'Very right wing'],
      would_rather_not_say: 'Would rather not say',
      county: 'County',
    },
    results: {
      my_constituency: 'My Constituency',
      constituency_size: 'You are one of %i volunteers in %s, can you help us reach %i?',
      constituency_size_one: 'You are the first volunteer in %s!. Can you help us find more?',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon",
      shareFacebook1: "% of the political ads I see on Facebook are from ",
      shareFacebook2: ". Install Who Targets Me in your browser to find out who's trying to win your vote with targeted social media ads. https://whotargets.me",
      shareTwitter1: "% of the political ads I see on Facebook are from ",
      shareTwitter2: ". Install Who Targets Me in your browser to find out who's trying to win your vote with targeted social media ads. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Website',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'T&Cs',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy Policy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  de: {
    who_targets_me: 'Wer bezahlt für meine Stimme?',
    loading: 'Daten werden geladen, vielen Dank für deine Geduld',
    register: {
      select_language: 'Bitte wählen Sie Ihre bevorzugte Sprache aus',
      terms: '<span>By continuing you agree to the <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'Ich stimme zu',
      back: 'Zurück',
      next: 'Nächster',
      country: 'Land',
      enter_country: 'Bitte geben Sie Ihr Land an',
      postcode: 'Postleitzahl',
      enter_postcode: 'Bitte geben Sie Ihre Postleitzahl ein',
      postcode_error: 'Es sieht so aus, als hätten Sie eine ungültige Postleitzahl eingegeben',
      gender: 'Dein Geschlecht',
      male: 'Männlich',
      female: 'Weiblich',
      other: 'Andere',
      years_of_age: 'Wie alt bist du (in Jahren)?',
      age: 'Alter',
      confirming: 'Bestätigen Sie Ihre Angaben',
      request_error: 'Der Server antwortete mit folgendem Fehler:',
      unknown_error: 'Unbekannter Fehler, falls anhalten Sie bitte in Kontakt!',
      share: 'Share Who Targets Me mit Ihren Freunden, um digitale Transparenz zu unterstützen',
      share1: 'Share the project',
      share2: ' to help your friends learn more about the targeted political ads they see.',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Überspringen',
      shareFacebook: '@WhoTargetsMe enthullt Dark Ads an der #BTW17 Finde heraus, welche Parteien auf dich zielen https://whotargets.me/de',
      shareTwitter: '@WhoTargetsMe enthullt Dark Ads an der #BTW17 Finde heraus, welche Parteien auf dich zielen https://whotargets.me/de',
      political_affiliation: 'Please choose your political affiliation',
    },
    results: {
      my_constituency: 'Mein Bundestagswahlkreis',
      constituency_size: 'Du bist einer von %i Freiwilligen in %s, kannst du uns helfen %i zu erreichen?',
      constituency_size_one: 'Glückwünsch! Du bist der/die erste/r Freiwillige in %s. Kannst du uns helfen, noch mehr zu finden?',
      no_results_explanation: 'Who Targets Me arbeitet im Hintergrund, um zu ermitteln, welche Werbung du siehst. Diese Seite wird mit Statistiken aktualisiert, sobald wir genug Daten gesammelt haben.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Webseite',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Bedingungen',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privatsphäre',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  es: {
    who_targets_me: '¿De quién soy el blanco?',
    loading: 'Cargando, gracias por tu paciencia',
    register: {
      welcome1: '¿De quién soy el blanco? ayuda a los ciudadanos a entender cómo la publicidad digital',
      welcome2: 'altamente segmentada se emplea con fines persuasivos.',
      welcome3: 'nos ayuda a mostrarte la versión correcta de ¿De quién soy el blanco?',
      welcome4: 'para que podamos conocer mejor tu sistema electoral y las próximas elecciones en tu país',
      select_language: "Por favor, selecciona tu idioma",
      terms: '<span>Al continuar aceptas las <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: "Acepto",
      back: "Volver",
      next: "Siguiente",
      country: "País",
      enter_country: "Por favor, introduce tu país de residencia",
      postcode: "Código postal",
      enter_postcode: "Por favor, introduce tu código postal",
      postcode_error: "Parece que has introducido un código postal no válido",
      gender: "Tu género",
      male: "Hombre",
      female: "Mujer",
      other: "Otro",
      years_of_age: "¿Qué edad tienes (en años)?",
      age: "Edad",
      confirming: "Estamos confirmando tus datos de registro",
      request_error: "El servidor ha respondido con el siguiente mensaje:",
      unknown_error: "Error desconocido, ¡Si persiste por favor contáctanos!",
      share: "Comparte ¿De quién soy el blanco? con tus amigos para ayudarles a descubrir la publicidad política a la que están siendo expuestos",
      share1: "Comparte tus resultados",
      share2: ' para ayudar a otros ciudadanos a descubrir la publicidad a la que están siendo expuestos',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: "Compartir en Facebook",
      shareOnTwitter: "Compartir en Twitter",
      skip: "Saltar",
      shareFacebook: "¿De quién soy el blanco? está investigando la publicidad política y electoral altamente segmentada en redes sociales y yo les estoy ayudando. Únete y descubre de quién eres el blanco https://whotargets.me",
      shareTwitter: "@WhoTargetsMe está investigando la publicidad electoral y política en redes sociales y yo les estoy ayudando. Únete y descubre de quién eres el blanco https://whotargets.me",
      political_affiliation: "Ideología política",
      political_affiliation_description: '¿Dirías que eres "de izquierdas" o "de derechas"?',
      us_labels: ["Sin afiliación política", "Muy de izquierdas", "De izquierdas", "De centro izquierda", "De centro", "De centro-derecha", "De derechas", "Muy de derechas" ],
      non_us_labels: ["Sin afiliación política", "Muy de izquierdas", "De izquierdas", "De centro izquierda", "De centro", "De centro-derecha", "De derechas", "Muy de derechas" ],
      would_rather_not_say: "Prefiero no decirlo",
      county: "País",
    },
    results: {
      my_constituency: "Mi circunscripción",
      constituency_size: "Ya eres uno de nuestros %i voluntarios en %s, ¿Puedes ayudarnos a alcanzar %i?",
      constituency_size_one: "Eres el primer voluntario de %s!. ¿Puedes ayudarnos a reclutar más?",
      no_results_explanation: "Los resultados aparecerán aquí cuando tengamos suficientes datos. Continúa usando Facebook con normalidad y vuelve a mirar esta sección en algunos días.",
      no_country_explanation1: "Te mostraremos resultados personalizados ",
      no_country_explanation2: " pronto. Mientras tanto, sigue usando Facebook con normalidad. Muchas gracias por participar en ¿De quién soy el blanco?",
      delete_request: "Si eliminas tus datos, no podremos usarlos para investigar. Tienes tres opciones:",
      data_deleted: "Hemos eliminado tus datos y no recopilaremos nuevos datos.",
      data_deleted2: 'Puedes eliminar la extensión de ¿De quién soy el blanco? clicando con el botón derecho del ratón en el icono en la barra de herramientas del navegador y seleccionando "Eliminar"',
      data_deleted3: 'Muchas gracias de nuevo por tu participación. Puedes seguir nuestro proyecto en Facebook, Twitter o email',
      delete_data: "Eliminar datos",
      delete_data_message: "Elimina todos los datos que has recopilado con ¿De quién soy el blanco? y tu perfil anónimo.",
      remove_WTM: "Eliminar",
      remove_WTM_message: 'Haz click con el botón derecho de tu ratón en el icono de la extensión de ¿De quién soy el blanco? y selecciona "Eliminar"',
      remove_WTM_message2: "Mantiene tus datos y tu perfil anónimo para que podamos seguir investigando.",
      cancel: "Cancelar",
      cancel_message: "Vuelve a la ventana anterior y continua usando ¿De quién soy el blanco?",
      uninstall: "Para desinstalar, haz click con el botón derecho en el icono de la extensión de ¿De quién soy el blanco?",
      shareFacebook1: "% de la publicidad política y electoral que veo en Facebook es de ",
      shareFacebook2: ". Instala ¿De quién soy el blanco? en tu navegador y descubre quién está tratando de conseguir tu voto con publicidad hipersegmentada en redes sociales https://whotargets.me",
      shareTwitter1: "% de la publicidad política y electoral que veo en Facebook es de ",
      shareTwitter2: ". Instala ¿De quién soy el blanco? en tu navegador y descubre quién está tratando de conseguir tu voto con publicidad hipersegmentada en redes sociales https://whotargets.me",
      results_screen1: "Eres el blanco de ", // You are being targeted by {party name}.
      results_screen2: "En total has visto ", // In total you've seen {quantity} political ads,
      results_screen3: " anuncios políticos o electorales, de los cuales ", //of which.
      results_screen4: " eran de ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Página Web',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Terminos',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacidad',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  it: {
    who_targets_me: 'Who Targets Me?',
    loading: 'In caricamento, grazie per la pazienza',
    register: {
      select_language: 'Seleziona la tua lingua preferita',
      terms: '<span>Procedendo con la registrazione accetti <a href="https://whotargets.me/en/terms/">i termini di utilizzo</a> e <a href="https://whotargets.me/en/privacy-policy/">la privacy policy</a></span>',
      agree: 'Accetto',
      back: 'Indietro',
      next: 'Prossimo',
      country: 'Paese',
      enter_country: 'Inserisci il tuo Paese di residenza',
      postcode: 'CAP',
      enter_postcode: 'Inserisci il tuo CAP',
      postcode_error: 'Il CAP inserito non sembra essere valido',
      gender: 'Il tuo genere',
      male: 'Uomo',
      female: 'Donna',
      other: 'Altro',
      years_of_age: 'Quanti anni hai?',
      age: 'Età',
      confirming: 'Conferma i dettagli inseriti',
      request_error: 'Il server ha restituito il seguente messaggio:',
      unknown_error: 'Errore sconosciuto, se dovesse accadere di nuovo non esitare a contattarci!',
      share: 'Condividi Who Targets Me con i tuoi amici per supportare la trasparenza digitale',
      shareOnFacebook: 'Condividi su Facebook',
      shareOnTwitter: 'Condividi su Twitter',
      skip: 'Salta',
      shareFacebook: '@WhoTargetsMe svela chi sta utilizzando campagne pubblicitarie politiche oscure. Scopri chi ti sta prendendo di mira https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe svela chi sta utilizzando campagne pubblicitarie politiche oscure. Scopri chi ti sta prendendo di mira https://whotargets.me/',
    },
    results: {
      my_constituency: 'La mia circoscrizione',
      constituency_size: 'Sei uno dei %i volontari nella tua circoscrizione (%s), puoi aiutarci a raggiungerne %i?',
      constituency_size_one: 'Tu sei il primo volontario in %s!. Puoi aiutarci a trovarne altri?',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Sito web',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Termini di utilizzo',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  hu: {
    who_targets_me: 'Célkeresztben',
    loading: 'Az oldal töltődik, kis türelmet kérünk',
    register: {
      select_language: 'Válasszon nyelvet',
      terms: '<span>A folytatással elfogadja a <a href="https://whotargets.me/en/terms/">felhasználási feltételeket</a> és <a href="https://whotargets.me/en/privacy-policy/">az adatkezelési irányelveket</a></span>',
      agree: 'Elfogadom',
      back: 'Vissza',
      next: 'Tovább',
      country: 'Ország',
      enter_country: 'Tartózkodási ország',
      postcode: 'Irányítószám',
      enter_postcode: 'Adja meg az irányítószámát',
      postcode_error: 'Az irányítószám formátuma nem megfelelő',
      gender: 'Nemed',
      male: 'Férfi',
      female: 'Nő',
      other: 'Egyéb',
      years_of_age: 'Hány éves?',
      age: 'Kor',
      confirming: 'Adataim megerősítése',
      request_error: 'A szerver a következő üzenettel tért vissza:',
      unknown_error: 'Ismeretlen hiba, ha továbbra is ezt tapasztalja, lépjen velünk kapcsolatba!',
      share: 'Segítsen növelni a digitális átláthatóságot! Ossza meg a Célkeresztben alkalmazást az ismerőseivel.',
      shareOnFacebook: 'Megosztom a Facebookon',
      shareOnTwitter: 'Megosztom a Twitteren',
      skip: 'Ezt most kihagyom',
      shareFacebook: 'A @WhoTargetsMe az online hirdetések sötét oldalát vizsgálja. Nézze meg, Önnek ki üzen. https://whotargets.me/',
      shareTwitter: 'A @WhoTargetsMe az online hirdetések sötét oldalát vizsgálja. Nézze meg, Önnek ki üzen. https://whotargets.me/',
      political_affiliation: 'Melyik politikai oldal áll Önhöz a legközelebb?',
      political_affiliation_description: 'A legtöbben jobb- és baloldalról beszélnek a politikában. Ön hogyan írná le a nézeteit?',
      us_labels: ['No affiliation', 'Erőteljesen baloldali', 'Mérsékelten baloldali', 'Kissé baloldali', 'Centrista', 'Kissé jobboldali', 'Mérsékelten jobboldali', 'Erőteljesen jobboldali'],
      non_us_labels: ['No affiliation', 'Erőteljesen baloldali', 'Mérsékelten baloldali', 'Kissé baloldali', 'Centrista', 'Kissé jobboldali', 'Mérsékelten jobboldali', 'Erőteljesen jobboldali'],
      would_rather_not_say: 'Nem akarok mondani',
    },
    results: {
      my_constituency: 'Választókörzetem',
      constituency_size: '%s körzetben %i önkéntesünk van, segítsen nekünk elérni, hogy ennyi legyen: %i!',
      constituency_size_one: 'Ön az első önkéntes itt: %s. Hívjon meg másokat is!',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Honlap',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Felhasználási feltételek',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Adatvédelem',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  ru: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Загрузка, спасибо за ваше терпение',
    register: {
      welcome1: 'Who Targets Me исследует скрытую рекламу,',
      welcome2: 'узнайте, кто нацелен на вас.',
      welcome3: 'Помогает показать вам правильную версию Who Targets Me.',
      welcome4: 'Чтобы мы знали, когда у вас будут следующие выборы.',
      select_language: 'Выберите нужный язык',
      terms: '<span>Продолжая, вы соглашаетесь с <a href="https://whotargets.me/en/terms/">условия и положения</a> и <a href="https://whotargets.me/en/privacy-policy/">политика конфиденциальности</a></span>',
      agree: 'Согласен',
      back: 'Назад',
      next: 'Вперед',
      country: 'Страна',
      enter_country: 'Выберите страну проживания',
      postcode: 'Почтовый индекс',
      enter_postcode: 'Укажите почтовый индекс',
      postcode_error: 'Похоже, вы ввели неверный почтовый индекс',
      gender: 'Ваш пол',
      male: 'Мужской',
      female: 'Женский',
      other: 'Другой',
      years_of_age: 'Сколько вам лет?',
      age: 'Возраст',
      confirming: 'Подтвердить данные',
      request_error: 'Сервер ответил следующим сообщением:',
      unknown_error: 'Неизвестная ошибка, если это повторится, пожалуйста, свяжитесь с нами!',
      share: 'Поделитесь проектом, чтобы помочь вашим друзьям узнать больше о политической рекламе, которую они видят.',
      share1: 'Поделиться проектом',
      share2: ' чтобы помочь вашим друзьям узнать больше о политической рекламе, которую они видят.',
      share3: 'Более %i человек в %s принимают участие в проекте Who Targets Me.',
      share4: 'Вы можете поделиться проектом, чтобы увеличить это число до %i',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Пропустить',
      shareFacebook: '@WhoTargetsMe исследует скрытую рекламу, узнайте, кто нацелен на вас https://whotargets.me/',
      shareTwitter: "@WhoTargetsMe исследует скрытую рекламу, узнайте, кто нацелен на вас https://whotargets.me/",
      political_affiliation: 'Ваши политические взгляды',
      political_affiliation_description: 'Большинство людей думает о политике, как о делении на  \'левых\' и \'правых\'. Как бы вы описали свои собственные взгляды?',
      us_labels: ['Нет принадлежности', 'Ультралиберальные', 'Умеренно либеральные', 'Слегка либеральные', 'Центристские', 'Слегка консервативные', 'Умеренно консервативные', 'Ультраконсервативные'],
      non_us_labels: ['Нет принадлежности', 'Ультралевые', 'Умеренно левые', 'Левоцентристские', 'Центристские', 'Правоцентристские', "Умеренно правые", "Ультраправые"],
      would_rather_not_say: "Предпочитаю не говорить",
      county: "Округ",
    },
    results: {
      my_constituency: 'Мои избиратели',
      constituency_size: 'Вы один из % добровольцев в %, можете ли вы помочь нам достичь %?',
      constituency_size_one: 'Вы первый волонтер из %!. Можете ли вы помочь нам найти больше?',
      no_results_explanation: 'Результаты появятся здесь, когда у нас будет достаточно данных. Продолжайте использовать Facebook в обычном режиме и возвращайтесь через несколько дней.',
      no_country_explanation1: "Мы предоставим персонализированные результаты",
      no_country_explanation2: " скоро. А пока продолжайте использовать Facebook в обычном режиме, и спасибо, что приняли участие в Who Targets Me.",
      delete_request: "Если вы удалите данные, то они будут недоступны для исследования. У вас есть три варианта:",
      data_deleted: "Ваши данные были удалены и новые данные не собираются.",
      data_deleted2: "Теперь вы можете удалить приложение, щелкнув правой кнопкой мыши по значку 'Who Targets Me' на панели инструментов браузера, и выбрать 'Удалить ...'.",
      data_deleted3: "Еще раз спасибо за участие. Вы можете продолжать следить за обновлениями проекта через Twitter, Facebook и рассылку электронной почты.",
      delete_data: "Удалить данные",
      delete_data_message: "Удалить все данные, которые были собраны с помощью Who Targets Me вместе с вашим анонимным профилем.",
      remove_WTM: "Удалить WTM",
      remove_WTM_message: "Щелкните правой кнопкой мыши по значку приложения и выберите 'Удалить ...'",
      remove_WTM_message2: "Сохранить ваши данные и анонимный профиль для исследований.",
      cancel: "Отменить",
      cancel_message: "Вернуться к предыдущему экрану и продолжить использовать Who Targets Me",
      uninstall: "Чтобы удалить, щелкните правой кнопкой мыши по значку расширения на панели инструментов.",
      shareFacebook1: "Я был мишенью для ",
      shareFacebook2: "Установите Who Targets Me, чтобы узнать, кто использует политическую рекламу в социальных сетях, чтобы получить ваш голос. https://whotargets.me",
      shareTwitter1: "Я был мишенью для ",
      shareTwitter2: ". Установите Who Targets Me, чтобы узнать, кто использует политическую рекламу в социальных сетях, чтобы получить ваш голос. https://whotargets.me",
      results_screen1: "К вам пытается обратиться партия ", // You are being targeted by {party name}.
      results_screen2: "В общей сложности вы видели ", // In total you've seen {quantity} political ads
      results_screen3: " политических рекламных объявлений, из которых ", //of which.
      results_screen4: " были от ", //{quantity} were from {party name}.
    },
    links: {
      website: {
        title: 'Веб-сайт',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Условия',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Конфиденциальность',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  lv: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Notiek ielāde, paldies par pacietību',
    register: {
      welcome1: 'Who Targets Me platforma palīdz saprast, kā sociālo mediju reklāma',
      welcome2: 'tiek izmantota, lai jūs ietekmētu.',
      welcome3: 'Palīdzi mums parādīt pareizo Who Targets Me versiju.',
      welcome4: 'Lai mēs zinātu, kad jums ir nākamās vēlēšanas.',
      select_language: 'Lūdzu, izvēlieties vēlamo valodu',
      terms: '<span>Turpinot jūs piekrītat <a href="https://whotargets.me/en/terms/">lietošanas noteikumiem</a> un <a href="https://whotargets.me/en/privacy-policy/">konfidencialitātes politikai</a></span>',
      agree: 'Piekrītu',
      back: 'Atpakaļ',
      next: 'Tālāk',
      country: 'Valsts',
      enter_country: 'Lūdzu, ievadiet savu valsti',
      postcode: 'Pasta indekss',
      enter_postcode: 'Lūdzu ievadiet savu pasta indeksu',
      postcode_error: 'Izskatās, ka ievadījāt nederīgu pasta indeksu',
      gender: 'Es esmu...',
      male: 'vīrietis',
      female: 'sieviete',
      other: 'cits',
      years_of_age: 'Cik jums ir gadu?',
      age: 'Vecums',
      confirming: 'Apstiprinām jūsu datus',
      request_error: 'Serveris atbildēja ar šādu ziņojumu:',
      unknown_error: 'Nezināma kļūda. Ja tā atkārtojas, lūdzu, sazinieties ar mums!',
      share: 'Pastāstiet par Who Targets Me saviem draugiem un atbalstiet mūsu darbu',
      share1: 'Dalies ar projektu',
      share2: ' Pastāsti par mums saviem draugiem, lai arī viņi varētu zināt vairāk par mērķētām politiskajām reklāmām.',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Izlaist',
      shareFacebook: '@WhoTargetsMe pēta tiešsaistes reklāmu tumšo tirgu - uzzini, kas ir mērķēts uz tevi https://whotargets.me/',
      shareTwitter: "@WhoTargetsMe pēta tiešsaistes reklāmu tumšo tirgu - uzzini, kas ir mērķēts uz tevi https://whotargets.me/",
      political_affiliation: 'Jūsu politiskā nostāja',
      political_affiliation_description: 'Lielākā daļa cilvēku politiskos uzskatus iedala  \'labējos\' un \'kreisajos\'. Kā jūs raksturotu savus uzskatus?',
      us_labels: ['Nav politiskās piederības', 'Ļoti liberāli uzskati', 'Liberāli uzskati', 'Daļēji liberāli uzskati', 'Centriski uzskati', 'Daļēji konservatīvi uzskati', 'Konservatīvi uzskati', 'Ļoti konservatīvi uzskati'],
      non_us_labels: ['Nav politiskās piederības', 'Izteikti labēji uzskati', 'Labēji uzskati', 'Daļēji labēji uzskati', 'Centriski uzskati', 'Daļēji kreisi uzskati', 'Kreisi uzskati', 'Ļoti kreisi uzskati'],
      would_rather_not_say: "Nevēlos uz šo jautājumu atbildēt",
      county: "Valsts",
    },
    results: {
      my_constituency: 'Mans vēlēšanu apgabals',
      constituency_size: 'Tu esi viens no %i brīvprātīgajiem %s, vai vari palīdzēt mums sasniegt %i?',
      constituency_size_one: 'Tu esi pirmais brīvprātīgais no %s! Vai vari mums palīdzēt atrast vairāk brīvprātīgo?',
      no_results_explanation: 'Who Targets Me darbojas fonā, lai noteiktu, kādas reklāmas jūs redzat. Šī lapa tiks atjaunināta ar statistiku, tiklīdz būsim savākuši pietiekami daudz datu.',
      no_country_explanation1: "Mēs jums sniegsim personalizētus rezultātus ",
      no_country_explanation2: " drīzumā. Tikmēr turpiniet izmantot Facebook kā ierasts, un liels paldies par Jūsu dalību Who Targets Me projektā.",
      delete_request: "Izdzēšot visu informāciju, tā vairs nebūs pieejama pētījumam. Jums ir trīs izvēles iespējas:",
      data_deleted: "Visa Jūsu savāktā informācija tiek izdzēsta un jauna informācija netiek iegūta",
      data_deleted2: "Jūs varat atvienot spraudni uzklikšķinot uz Who Targets Me ikonas jūsu interneta pārlūka rīkjoslā, un izvēloties  'Remove...'",
      data_deleted3: "Paldies Jums par dalību mūsu projektā. Jūs varat turpināt sekot līdzi mūsu darbībai Twitter, Facebook, kā arī pieteikties informatīvajiem epastiem.",
      delete_data: "Dzēst datus",
      delete_data_message: "Dzēš visu informāciju, ko esat ieguvis izmantojot Who Targets Me, ieskaitot Jūsu anonīmo progilu.",
      remove_WTM: "Noņemt WTM",
      remove_WTM_message: "Labais klikšķis uz aplikācijas ikonas un tad izvēlaties'Remove...'",
      remove_WTM_message2: "Saglabā jūsu datus un anonīmo profilu pētījumam.",
      cancel: "Atcelt",
      cancel_message: "Doties atpakaļ uz iepriekšējo lapu un turpināt izmnantot Who Targets Me",
      uninstall: "Lai atinstalētu, ar labo peles pogu klikšķiniet uz aplikācijas ikonas jūsu rīkjoslā.",
      shareFacebook1: "Kā mērķauditoriju mani izvēlas: ",
      shareFacebook2: ". Instalē Who Targets Me, lai noskaidrotu kuru politisko spēku sociālo tīklu reklāmas tiek izmantotas, lai iegūtu Tavu balsi. https://whotargets.me",
      shareTwitter1: "Kā mērķauditoriju mani izvēlas ",
      shareTwitter2: ". Instalē Who Targets Me, lai noskaidrotu kuru politisko spēku sociālo tīklu reklāmas tiek izmantotas, lai iegūtu Tavu balsi. https://whotargets.me",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Mājaslapa',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Noteikumi',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Konfidencialitāte',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  pt: {
    who_targets_me: 'Você na mira',
    loading: 'Carregando, obrigado por esperar',
    register: {
      welcome1: 'Who Targets Me helps people understand how targeted social',
      welcome2: 'media advertising is used to persuade them.',
      welcome3: 'helps us to show you the right version of Who Targets Me',
      welcome4: 'so we know your next election and voting system',
      select_language: 'Por favor, selecione seu idioma preferido',
      terms: '<span>Ao continuar, você estará concordando com os <a href="https://whotargets.me/en/terms/">termos de uso</a> e <a href="https://whotargets.me/en/privacy-policy/">Política de Privacidade</a></span>',
      agree: 'Eu concordo',
      back: 'Voltar',
      next: 'Avançar',
      country: 'País',
      enter_country: 'Por favor, digite seu país de residência',
      postcode: 'CEP',
      enter_postcode: 'Por favor, digite seu CEP',
      postcode_error: 'Você digitou um CEP inválido',
      gender: 'Seu gênero',
      male: 'masculino',
      female: 'feminino',
      other: 'outro',
      years_of_age: 'Qual a sua idade?',
      age: 'Idade',
      confirming: 'Confirme suas informações',
      request_error: 'O servidor respondeu com a seguinte mensagem:',
      unknown_error: 'Erro desconhecido. Se persistir, por favor, entre em contato!',
      share: 'Compartilhe esse projeto para ajudar seus amigos a aprender mais sobre marketing político direcionado.',
      share1: 'Compartilhe o projeto',
      share2: ' para ajudar seus amigos a aprender mais sobre marketing político direcionado.',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Pular',
      shareFacebook: '@WhoTargetsMe e @internetlabbr estão investigando propaganda eleitoral no Facebook, descubra de quem você está na mira https://whotargets.me',
      shareTwitter: '@WhoTargetsMe e @internetlabbr estão investigando propaganda eleitoral no Facebook, descubra de quem você está na mira https://whotargets.me',
      political_affiliation: 'Suas posições políticas',
      political_affiliation_description: 'A maioria das pessoas pensam em política em termos de \'esquerda (progressista)\' e \'direita (conservadora)\'. Nestes termos como você descreveria sua posição?',
      us_labels: ['Sem afiliação', 'Muito liberal', 'Liberal moderado', 'Pouco liberal', 'Centro', 'Pouco conservador', 'Conservador moderado', 'Muito conservador'],
      non_us_labels: ['Sem afiliação', 'Extrema esquerda', 'Esquerda', 'Centro-esquerda', 'Centro', 'Centro-direita', 'Direita', 'Extrema direita'],
      would_rather_not_say: 'Prefiro não dizer',
      county: 'Estado',
    },
    results: {
      my_constituency: 'Meu domicílio eleitoral',
      constituency_size: 'Você é um dos %i voluntários em %s, você poderia nos ajudar a chegar a %i?',
      constituency_size_one: 'Você é o primeiro voluntário em %s!. Você poderia nos ajudar a encontrar outros?',
      no_results_explanation: 'Os resultados serão mostrados aqui quando nós coletarmos dados suficientes. Continue usando o Facebook e verifique novamente em alguns dias.',
      no_country_explanation1: "Nós iremos trazer resultados personalizados para ",
      no_country_explanation2: " em breve. Enquanto isso, continue usando o Facebook e obrigado por participar do Você Na Mira.",
      delete_request: "Deletar seus dados os torna indisponíveis para pesquisa. Você tem três opções:",
      data_deleted: "Seus dados foram deletados e nenhum novo dado será coletado.",
      data_deleted2: "Você pode remover a extensão clicando com o botão direito no ícone do Você Na Mira no seu navegador, e selecionando 'Remover do Chrome'",
      data_deleted3: "Obrigado por participar. Você pode continuar acompanhando atualizações do projeto pelo Twitter e pelo Facebook.",
      delete_data: "Deletar dados",
      delete_data_message: "Deletar todos os dados coletados pelo Você Na Mira junto com seu perfil anônimo.",
      remove_WTM: "Remover Você Na Mira",
      remove_WTM_message: "Clique no ícone da extensão e selecione 'Remover do Chrome'",
      remove_WTM_message2: "Preservar seus dados e perfil anônimo para pesquisa.",
      cancel: "Cancelar",
      cancel_message: "Voltar para a tela anterior e continuar usando Você Na Mira",
      uninstall: "Para desinstalar, clique com o botão direito no ícone da extensão na barra de ferramentas do seu navegador",
      shareFacebook1: "Eu estou na mira de ",
      shareFacebook2: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://whotargets.me",
      shareTwitter1: "Eu estou na mira de ",
      shareTwitter2: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://whotargets.me",
      shareFacebook2BR: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://vocenamira.org.br",
      shareTwitter2BR: ". Instale o Você Na Mira para descobrir quem está usando propaganda política nas redes sociais para ganhar seu voto. https://vocenamira.org.br",
      results_screen1: "You are being targeted by ", // You are being targeted by {party name}.
      results_screen2: "In total you've seen ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Site',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Termos de uso',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Política de privacidade',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  se: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Laddar, tack för att du väntar',
    register: {
      welcome1: 'Who Targets Me hjälper människor/användare att förstå hur riktade',
      welcome2: 'annonser i sociala medier används för att påverka dem.',
      welcome3: 'Hjälper oss att visa rätt version av Who Targets Me.',
      welcome4: 'Så vi vet ert nästa val och kan ert valsystem.',
      select_language: 'Välj språk',
      terms: '<span>Genom att fårtsätta så godkänner du  <a href="https://whotargets.me/en/terms/">användarvilkoren</a> och <a href="https://whotargets.me/en/privacy-policy/">integritetspolicyn</a></span>',
      agree: 'Jag godkänner',
      back: 'Tillbaka',
      next: 'Nästa',
      country: 'Land',
      enter_country: 'Välj ditt land',
      postcode: 'Postnummer',
      enter_postcode: 'Vänligen ange ditt postnummer',
      postcode_error: 'Det verkar som att du angav ett felaktigt postnummer',
      gender: 'Kön',
      male: 'Man',
      female: 'Kvinna',
      other: 'Annat',
      years_of_age: 'Hur gammal är du (antal år)?',
      age: 'Ålder',
      confirming: 'Bekräfta dina uppgifter',
      request_error: 'Servern returnerade följande meddelande:',
      unknown_error: 'Okänt fel, om felet kvarstår var vänlig kontakta oss!',
      share: 'Dela projektet och hjälp dina vänner att lära sig mer om de riktade politiska annonser de ser.',
      share1: 'Dela dina resultat',
      share2: ' för att hjälpa människor att lära sig mer om riktade politiska annonser.',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Hoppa över',
      shareFacebook: '@Who Targets Me undersöker politiska annonser i sociala medier. Jag hjälper dem. Gör det du också och få reda på dig vilka som riktar sina annonser mot dig: https://whotargets.me/',
      shareTwitter: '@@WhoTargetsMe undersöker politiska annonser i sociala medier. Jag hjälper dem. Gör det du också och få reda på dig vilka som riktar sina annonser mot dig: https://whotargets.me/',
      political_affiliation: 'Dina politiska åsikter',
      political_affiliation_description: 'De flesta tänker på politik som en skala från vänster till höger. Hur skulle du beskriva dina egna åsikter?',
      us_labels: ['Inga sympatier', 'Mycket liberal', 'Liberal', 'Lite liberal', 'Mitten', 'Lite konservativ', 'Konservativ', 'Mycket konservativ'],
      non_us_labels: ['Inga sympatier', 'Mycket vänster', 'Vänster', 'Lite vänster', 'Mitten', 'Lite höger', 'Höger', 'Mycket höger'],
      would_rather_not_say: 'Jag avstår',
      county: 'Län',
    },
    results: {
      my_constituency: 'Min valkrets',
      constituency_size: 'Du är en av %i frivilliga i %s, kan du hjälpa oss nå %i?',
      constituency_size_one: 'Du är den första frivilliga i %s! Kan du hjälpa oss hitta fler?',
      no_results_explanation: 'Resultaten kommer att visas här när vi har tillräckligt med data. Fortsätt att använda Facebook som vanligt och titta tillbaka här om ett par dagar.',
      no_country_explanation1: "Vi kommer snart visa personliga resultat to ",
      no_country_explanation2: " Fortsätt att använda Facebook som vanligt och tack för att du deltar i Who Targets Me.",
      delete_request: "Genom att radera din data är den inte längre tillgängligt för analys. Du har tre val:",
      data_deleted: "Din data har raderats och ingen ny data samlas in.",
      data_deleted2: "Du kan nu avinstallera tillägget genom att höger-klicka Who Targets Me-ikonen i webbläsarens verktygsmeny och välja 'Avinstallera...'",
      data_deleted3: "Tack igen för att du deltar. Du kan fortsätta att följa projektet via Twitter, Facebook och vår email-lista.",
      delete_data: "Radera data",
      delete_data_message: "Radera all data som du har samlat in med Who Targets Me, inklusive din anonyma profil.",
      remove_WTM: "Radera WTM",
      remove_WTM_message: "Höger-klicka tilläggets ikon och välj 'Avinstallera...'",
      remove_WTM_message2: "Behåller din data och din anonyma profil för analys.",
      cancel: "Avbryt",
      cancel_message: "Gå tillbaka till föregående sida och fortsätt använda Who Targets Me",
      uninstall: "För att avinstallera, höger-klicka ikonen för tillägg",
      shareFacebook1: "% av de politiska annonserna jag ser på Facebook är från ",
      shareFacebook2: ". Installera Who Targets Me för att förstå vem som använder politiska annonser i sociala medier för att vinna din röst. https://whotargets.me",
      shareTwitter1: "% av de politiska annonserna jag ser på Facebook är från ",
      shareTwitter2: ". Installera Who Targets Me för att förstå vem som använder politiska annonser i sociala medier för att vinna din röst. https://whotargets.me",
      results_screen1: " riktar sina annonser mot mig ", // You are being targeted by {party name}.
      results_screen2: "Du har sammanlagt sett ", // In total you've seen {quantity} political ads,
      results_screen3: " politiska annonser där ", //of which.
      results_screen4: " är från ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Website',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Användarvillkor',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Integritetspolicy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  ua: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Триває завантаження... дякуємо за ваш час',
    register: {
      welcome1: 'Who Targets Me допомагає зрозуміти як спрямована соціальна',
      welcome2: ' реклама використовується у медіа.',
      welcome3: 'це допоможе показати вам відповідну версію Who Targets Me.',
      welcome4: 'щоб ми мали інформацію про наступні вибори у вашому регіоні та виборчу систему',
      select_language: 'Оберіть мову',
      terms: '<span>Продовжуючи користуватися додатком, ви надаєте згоду з <a href="https://whotargets.me/en/terms/">Умовами та Правилами користування</a> та <a href="https://whotargets.me/en/privacy-policy/">політикою конфіденційності</a>.</span>',
      agree: 'Погоджуюсь',
      back: 'Назад',
      next: 'Вперед',
      country: 'Країна',
      enter_country: 'Оберіть вашу країну',
      postcode: 'Поштовий індекс',
      enter_postcode: 'Будь ласка, вкажіть свій поштовий індекс',
      postcode_error: 'Схоже, що ви ввели недійсний поштовий індекс',
      gender: 'Ваша стать',
      male: 'Чоловік',
      female: 'Жінка',
      other: 'Інше',
      years_of_age: 'Ваш вік (у роках)?',
      age: 'Вік',
      confirming: 'Триває збереження даних',
      request_error: 'З сервера надійшла наступна відповідь:',
      unknown_error: "Невідома помилка. Якщо ви побачите це повідомлення ще раз, будь ласка, зв'яжіться з нами!",
      share: 'Поділіться проектом, щоб допомогти своїм друзям дізнатися більше про цільову політичну рекламу, яку вони бачать.',
      share1: 'Поділитися своїми результатами',
      share2: ' щоб допомогти дізнатися більше про цільову політичну рекламу.',
      share3: '%s: більше %i чоловік взяли участь у проекті Who Targets Me.',
      share4: 'Ви можете поділитися проектом, щоб допомогти збільшити кількість учасників до %i.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Пропустити',
      shareFacebook: 'WhoTargetsMe досліджує приховану рекламу. Дізнайтеся, хто таргетує вас https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe досліджує приховану рекламу. Дізнайтеся, хто таргетує вас https://whotargets.me/',
      political_affiliation: 'Ваші політичні погляди',
      political_affiliation_description: 'Більшість людей поділяє політичне середовище на \'лівих\' та \'правих\'. Як би ви охарактеризували свої політичні вподобання?',
      us_labels: ['Немає', 'Дуже ліберальні', 'Помірно ліберальні', 'Дещо ліберальні', 'Центристські', 'Дещо консервативні', 'Помірно консервативні', 'Дуже консервативні'],
      non_us_labels: ['Немає', 'Крайні ліві', 'Помірно ліві', 'Дещо ліві', 'Центристські', 'Дещо праві', 'Помірно праві', 'Крайні праві'],
      would_rather_not_say: 'Не бажаю відповідати',
      county: 'Виборчий округ',
    },
    results: {
      my_constituency: 'Мій виборчий округ',
      constituency_size: "Ви є одним з %i волонтерів у %s. Чи можете ви допомогти нам зв'язатися з %i?",
      constituency_size_one: 'Ви перший волонтер у %s!. В вас є можливість долучити інших?',
      no_results_explanation: "Результати з'являться тут, коли в нас буде достатньо даних. Продовжуйте користуватися Facebook у звичайному режимі та перевірте додаток через декілька днів.",
      no_country_explanation1: "Незабаром персоніфіковані результати будуть доступні в ",
      no_country_explanation2: " . Наразі продовжуйте користуватися Facebook у звичайному режимі та дякуємо за участь у проекті Who Targets Me.",
      delete_request: "Видалення ваших даних зробить іх недоступними для використання у дослідженнях. У вас є три варіанти:",
      data_deleted: "Ваші дані видалені. Збір нових даних припинено.",
      data_deleted2: "Зараз ви можете видалити додаток - натисніть значок Who Targets Me правою кнопкою миші у браузері та оберіть 'Видалити...'",
      data_deleted3: "Ще раз дякуємо за вашу участь у проекті. Ви можете продовжувати слідкувати за оновленнями у Twitter, Facebook або за допомогою електронної розсилки.",
      delete_data: "Видалити дані",
      delete_data_message: "Видаляє усі дані, які були зібрані Who Targets Me за вашою допомогою, а також ваш анонімний профіль.",
      remove_WTM: "Видалити WTM",
      remove_WTM_message: "Натисніть правою кнопкою миші на значок додатку та оберіть 'Видалити...'",
      remove_WTM_message2: "Зберігає зібрані дані та ваш анонімний профіль для досліджень.",
      cancel: "Скасувати",
      cancel_message: "Повернутися до попереднього екрану та продовжити користуватися Who Targets Me",
      uninstall: "Щоб видалити додаток, натисніть правою кнопкою миші на значок додатку",
      shareFacebook1: "% політичних оголошень, що я бачу на Facebook, є від ",
      shareFacebook2: ". Встановіть Who Targets Me у вашому браузері, щоб дізнатися хто намагається завоювати ваш голос за допомогою таргетованої політичної реклами. https://whotargets.me",
      shareTwitter1: "% політичних оголошень, що я бачу на Facebook, є від ",
      shareTwitter2: ". Встановіть Who Targets Me у вашому браузері, щоб дізнатися хто намагається завоювати ваш голос за допомогою таргетованої політичної реклами. https://whotargets.me",
      results_screen1: "Вас таргетує ", // You are being targeted by {party name}.
      results_screen2: "Загалом ви побачили ", // In total you've seen {quantity} political ads,
      results_screen3: " політичних оголошень, з яких ", //of which.
      results_screen4: " були від ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Вебсайт',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Умови та Правила',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Політика конфіденційності',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  fi: {
    who_targets_me: 'Who Targets Me? Finland',
    loading: 'Ladataan, kiitos kärsivällisyydestä',
    register: {
      welcome1: 'Who Targets Me auttaa ymmärtämään millaisilla sosiaalisen median viesteillä',
      welcome2: 'ihmisiin vaikutetaan vaalien alla.',
      welcome3: 'auttaa meitä näyttämään sinulla oikean version Who Targets Me -sovelluksesta',
      welcome4: 'niin että tiedämme milloin seuraavat vaalit ovat tapahtumassa ja millä vaalijärjestelmällä',
      select_language: 'Valitse kielesi',
      terms: '<span>Jatkamalla tästä eteenpäin hyväksyt myös <a href="https://whotargets.me/en/terms/">ohjelmiston käyttöehdot</a> ja <a href="https://whotargets.me/en/privacy-policy/">yksityisyyskäytäntömme</a></span>',
      agree: 'Hyväksyn',
      back: 'Takaisin',
      next: 'Seuraava',
      country: 'Maa',
      enter_country: 'Valitse maasi',
      postcode: 'Postinumero',
      enter_postcode: 'Täytä postinumerosi',
      postcode_error: 'Näyttää siltä, että täyttämäsi postinumero on virheellinen',
      gender: 'Sukupuolesi',
      male: 'Mies',
      female: 'Nainen',
      other: 'Muu',
      years_of_age: 'Kuinka vanha olet (vuosissa)?',
      age: 'Ikä',
      confirming: 'Varmistamme tietosi',
      request_error: 'Palvelin vastasi seuraavalla viestillä:',
      unknown_error: 'Tuntematon virhe - jos tämä jatkuu, ota yhteyttä!',
      share: 'Jaa hanke, niin ystäväsi voivat myös oppia heihin kohdistuvasta some-viestinnästä.',
      share1: 'Jaa tuloksesi',
      share2: ' niin voit auttaa muita oppimaan heihin kohdistetusta poliittisesta viestinnästä',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Ohita',
      shareFacebook: 'Who Targets Me selvittää somessa tapahtuvaa poliittista viestintää. Minä olen hankkeessa mukana. Liity joukkoon ja selvitä kuka yrittää vaikuttaa sinuun: https://whotargets.me',
      shareTwitter: '@Who Targets Me selvittää somessa tapahtuvaa poliittista viestintää. Minä olen hankkeessa mukana. Liity joukkoon ja selvitä kuka yrittää vaikuttaa sinuun: https://whotargets.me',
      political_affiliation: 'Poliittiset näkemyksesi',
      political_affiliation_description: 'Politiikkaan kuuluu ajatus \'vasemmistosta\' ja \'oikeistosta\'. Kuinka kuvailisit omia näkemyksiäsi?',
      us_labels: ['Sitoutumaton', 'Hyvin liberaali', 'Melko liberaali', 'Hieman liberaali', 'Keskellä', 'Hieman konservatiivinen', 'Melko konservatiivinen', 'Hyvin konservatiivinen'],
      non_us_labels: ['Sitoutumaton', 'Hyvin vasemmalla', 'Melko vasemmalla', 'Hieman vasemmalla', 'Keskellä', 'Hieman oikealla', 'Melko oikealla', 'Hyvin oikealla'],
      would_rather_not_say: 'Mieluummin en vastaa',
      county: 'Kunta',
    },
    results: {
      my_constituency: 'Vaalipiirini',
      constituency_size: 'Olet yksi %i vapaaehtoisesti %sssa, voitko auttaa meitä saavuttamaan %i?',
      constituency_size_one: 'Olet ensimmäinen vapaaehtoinen %ssa! Voitko auttaa meitä löytämään lisää?',
      no_results_explanation: 'Tulokset näytetään täällä kun meillä on riittävästi dataa. Jatka Facebookin käyttöä tyypilliseen tapaan, ja katso uudestaan muutaman päivän päästä.',
      no_country_explanation1: "Tulemme tuomaan henkilökohtaiset tulokset ",
      no_country_explanation2: " lle pian. Ennen sitä, jatka Facebookin käyttöä tyypilliseen tapaan. Kiitos osallistumisesta.",
      delete_request: "Jos tietosi poistetaan, niitä ei voida käyttöö yleishyödyllisessä tutkimuksessa. Sinulla on kolme vaihtoehtoa:",
      data_deleted: "Tietosi on nyt poistettu ja uutta tietoa ei enää kerätä.",
      data_deleted2: "Voit nyt poistaa ohjelmiston oikealla napautuksella Who Targets Me -ikoniin selaimesi työkalupalkissa, ja valitsemalla 'Poista..'",
      data_deleted3: "Suuri kiitos osallistumisesta. Voit seurata hankkeen edistymistä Twitterin, Facebookin ja sähköpostilistamme kautta.",
      delete_data: "Poista tiedot",
      delete_data_message: "Poistaa kaikki tiedot, jotka olet lähettänyt hankkeen tietokantaan, mukaanlukien oman anonyymin profiilisi.",
      remove_WTM: "Poista WTM",
      remove_WTM_message: "Paina oikealla napilla ohjelmiston ikonia ja valitse 'Poista'",
      remove_WTM_message2: "Säilyttää tietosi ja anonyymin profiilisi tutkimusta varten.",
      cancel: "Peruuta",
      cancel_message: "Mene takaisin edelliseen ruutun ja jatka Who Targets Me:n käyttöä",
      uninstall: "Poistaaksesi asennuksen, paina oikealla napilla ohjelmiston ikonia",
      shareFacebook1: "% poliittisista mainoksista jotka näen Facebookissa ovat lähteestä ",
      shareFacebook2: ". Asenna Who Targets Me selaimeesi saadaksesi selville kuinka sinuun on yritetty vaikuttaa vaalien alla. https://whotargets.me",
      shareTwitter1: "% poliittisista mainoksista jotka näen Facebookissa ovat lähteestä ",
      shareTwitter2: ". Asenna Who Targets Me selaimeesi saadaksesi selville kuinka sinuun on yritetty vaikuttaa vaalien alla. https://whotargets.me",
      results_screen1: "Sinuun kohdistetaan viestejä seuraavilta tahoilta ", // You are being targeted by {party name}.
      results_screen2: "Yhteensä olet nähnyt ", // In total you've seen {quantity} political ads,
      results_screen3: " poliittista mainosta, joista ", //of which.
      results_screen4: " olivat peräisin ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Verkkosivut',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Käyttöehdot',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Yksityisyyskäytännöt',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  fr: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Chargement en cours, patienter',
    register: {
      welcome1: 'Who Targets Me aide les gens à comprendre',
      welcome2: 'comment la publicité ciblée est utilisée sur les médias sociaux pour les persuader.',
      welcome3: 'Nous aide à vous montrer la bonne version de Who Targets Me',
      welcome4: 'nous savons ainsi quand sont vos prochaines élections et quel est votre système de vote',
      select_language: 'Sélectionnez votre langue',
      terms: '<span>En procédant, vous acceptez nos <a href="https://whotargets.me/en/terms/">conditions générales</a> et notre <a href="https://whotargets.me/en/privacy-policy/">politique de confidentialité</a></span>',
      agree: 'Accepter',
      back: 'Précédent',
      next: 'Suivant',
      country: 'Pays',
      enter_country: 'Sélectionner votre pays',
      postcode: 'Code postal',
      enter_postcode: 'Veuillez saisir votre code postal',
      postcode_error: 'Il semble que vous ayez saisi un code postal invalide',
      gender: 'Votre sexe',
      male: 'Homme',
      female: 'Femme',
      other: 'Autre',
      years_of_age: 'Quel âge avez-vous (en années) ?',
      age: 'Âge',
      confirming: 'Confirmer vos détails',
      request_error: 'Le serveur a répondu avec le message suivant:',
      unknown_error: 'Erreur inconnue : si elle persiste, veuillez-nous contacter!',
      share: 'Partagez le projet pour aider vos amis à en savoir plus sur les annonces politiques ciblées qu’ils voient.',
      share1: 'Partagez vos résultats',
      share2: ' pour aider les gens à découvrir les annonces politiques ciblées.',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Skip',
      shareFacebook: 'Who Targets Me étudie les annonces politiques des médias sociaux. Je les aide. Joignez-vous à moi et découvrez de qui vous êtes la cible: https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe étudie les annonces politiques des médias sociaux. Je les aide. Joignez-vous à moi et découvrez de qui vous êtes la cible: https://whotargets.me',
      political_affiliation: 'Vos opinions politiques',
      political_affiliation_description: 'Pour la plupart des gens, la politique est une question de \'gauche\' et de \'droite\'. Comment décririez-vous votre propre opinion ?',
      us_labels: ['Aucune affiliation', 'Très libéral', 'Modérément libéral', 'Légèrement libéral', 'Centre', 'Légèrement conservateur', 'Modérément conservateur', 'Très conservateur'],
      non_us_labels: ['Aucune affiliation', 'Très à gauche', 'Modérément à gauche', 'Légèrement à gauche', 'Centre', 'Légèrement à droite', 'Modérément à droite', 'Très à droite'],
      would_rather_not_say: 'Préfère ne rien dire',
      county: 'Départment',
    },
    results: {
      my_constituency: 'My Constituency',
      constituency_size: 'Vous êtes l’un des %i bénévoles en %s; pouvez-vous nous aider à toucher %i?',
      constituency_size_one: 'Vous êtes le premier bénévole en %s! Pouvez-vous nous aider à en trouver d’autres ?',
      no_results_explanation: 'Les résultats apparaîtront ici lorsque nous aurons suffisamment de données. Continuez d’utiliser Facebook comme d’habitude et vérifiez de nouveau dans quelques jours.',
      no_country_explanation1: "Nous présenterons bientôt des résultats personnalisés en ",
      no_country_explanation2: " . Entretemps, continuez d’utiliser Facebook comme d’habitude. Nous vous remercions d’avoir participé à Who Targets Me.",
      delete_request: "Si vous supprimez vos données, celles-ci ne seront plus disponibles pour la recherche. Vous avez trois choix:",
      data_deleted: "Vos données ont été supprimées et aucune nouvelle donnée ne sera recueillie.",
      data_deleted2: "Vous pouvez supprimer maintenant l’extension par un clic droit sur l’icône Who Targets Me dans la barre d’outils de votre navigateur et en sélectionnant 'Supprimer...'",
      data_deleted3: "Merci pour votre participation. Vous pouvez continuer de suivre les mises à jour du projet sur Twitter, Facebook et notre liste de distribution par mail.",
      delete_data: "Supprimer les données",
      delete_data_message: "Supprime toutes les données que vous avez recueillies avec Who Targets Me et avec votre profil anonyme.",
      remove_WTM: "Supprimer WTM",
      remove_WTM_message: "Faites un clic droit sur l’icône d’extension et sélectionnez 'Supprimer...'",
      remove_WTM_message2: "Conserve vos données et votre profil anonyme pour la recherche.",
      cancel: "Annuler",
      cancel_message: "Retournez à l’écran précédent et continuez en utilisant Who Targets Me",
      uninstall: "Pour désinstaller, faites un clic droit sur l’icône d’extension",
      shareFacebook1: "% des annonces politiques que je vois sur Facebook viennent de ",
      shareFacebook2: ". Installez Who Targets Me dans votre navigateur pour découvrir qui essaie de gagner votre vote à travers des annonces politiques ciblées sur les médias sociaux. https://whotargets.me",
      shareTwitter1: "% des annonces politiques que je vois sur Facebook viennent de ",
      shareTwitter2: ". Installez Who Targets Me dans votre navigateur pour découvrir qui essaie de gagner votre vote à travers des annonces politiques ciblées sur les médias sociaux. https://whotargets.me",
      results_screen1: "Vous êtes la cible de ", // You are being targeted by {party name}.
      results_screen2: "En tout, vous avez vu ", // In total you've seen {quantity} political ads,
      results_screen3: " annonces politiques, dont ", //of which.
      results_screen4: " viennent de ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Website',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'T&Cs',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy Policy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  nl: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Aan het laden, bedankt voor uw geduld',
    register: {
      welcome1: 'Who Targets Me helpt u te begrijpen hoe doelgerichte social',
      welcome2: 'media advertenties proberen u te overtuigen',
      welcome3: 'Help ons alstublieft met het selecteren van de juist versie van Who Targets Me',
      welcome4: 'zodat wij uw eerstvolgende verkiezingen en kiessysteem kunnen bepalen',
      select_language: 'Kies uw taal',
      terms: '<span>Door verder te gaan ga je akkoord met de <a href="https://whotargets.me/en/terms/">voorwaarden</a> and <a href="https://whotargets.me/en/privacy-policy/">de privacyverklaring</a></span>',
      agree: 'Akkoord',
      back: 'Vorige',
      next: 'Volgende',
      country: 'Land',
      enter_country: 'Kies uw land',
      postcode: 'Postcode',
      enter_postcode: 'Wat is uw postcode?',
      postcode_error: 'Het lijkt erop dat u een ongeldige postcode heeft ingevoerd',
      gender: 'Wat is uw geslacht?',
      male: 'Man',
      female: 'Vrouw',
      other: 'Anders',
      years_of_age: 'Wat is uw leeftijd (in jaren)?',
      age: 'Leeftijd',
      confirming: 'Bevestig uw gegevens',
      request_error: 'De server geeft het volgende bericht:',
      unknown_error: 'Onbekende fout. Als dit aanhoudt, neem a.u.b. contact op',
      share: 'Deel het project en leer uw vrienden meer over de doelgerichte advertenties die zij zien',
      share1: 'Deel uw resultaten',
      share2: ' en leer uw vrienden meer over de doelgerichte advertenties die zij zien',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Overslaan',
      shareFacebook: 'Who Targets Me doet onderzoek naar politieke advertenties op social media. Ik help ze hierbij. Doe ook mee en ontdek wie u probeert te bereiken. https://whotargets.me',
      shareTwitter: '@WhoTargetsMe doet onderzoek naar politieke advertenties op social media. Ik help ze hierbij. Doe ook mee en ontdek wie u probeert te bereiken. https://whotargets.me',
      political_affiliation: 'Uw politieke opvattingen',
      political_affiliation_description: "De meeste mensen denken in politieke termen als \'links\' en \'rechts\'. Hoe zou u uw politieke opvattingen omschrijven?",
      us_labels: ['Geen mening', 'Zeer liberaal', 'Relatief liberaal', 'Ietwat liberaal', 'Centrum', 'Ietwat conservatief', 'Relatief conservatief', 'Zeer conservatief'],
      non_us_labels: ['Geen mening', 'Zeer links', 'Overwegend links', 'Ietwat links', 'Centrum', 'Ietwat rechts', 'Overwegend rechts', 'Zeer rechts'],
      would_rather_not_say: 'Zeg ik liever niet',
      county: 'Provincie',
    },
    results: {
      my_constituency: 'Gementee',
      constituency_size: 'U bent één van de %i vrijwilligers in %s. Kunt u ons helpen om %i te bereiken?',
      constituency_size_one: 'U bent de eerste vrijwilliger in %s! Kunt u ons helpen aan meer vrijwilligers?',
      no_results_explanation: 'Resultaten verschijnen hier zodra we genoeg data verzameld hebben. Blijf Facebook zoals normaal gebruiken en check de resultaten nog eens over een paar dagen.',
      no_country_explanation1: "We zullen snel gepersonaliseerde data kunnen leveren in ",
      no_country_explanation2: " . Blijf Facebook ondertussen gebruiken zoals normaal en bedankt voor uw deelname aan Who Targets Me",
      delete_request: "Het verwijderen van uw data maakt het onbeschikbaar voor onderzoek. U hebt drie keuzes:",
      data_deleted: "Uw data is verwijderd en er wordt geen nieuwe data meer verzameld.",
      data_deleted2: "U kunt de web-extensie verwijderen door met uw rechtermuisknop te klikken op het Who Targets Me symbool in uw toolbar, en kies 'Verwijder...'",
      data_deleted3: "Wederom bedankt voor uw deelname. U kunt updates over het project blijven volgen via Twitter, Facebook en onze e-maillijst.",
      delete_data: "Verwijder data",
      delete_data_message: "Verwijder zowel alle data die u verzameld heeft met Who Targets Me als uw anonieme profiel",
      remove_WTM: "Verwijder WTM",
      remove_WTM_message: "Rechtsklik op het webextensie symbool en kies 'Verwijder...'",
      remove_WTM_message2: "Bewaar uw data en anonieme profiel voor onderzoek.",
      cancel: "Annuleer",
      cancel_message: "Terug naar het vorige scherm en blijf Who Targets Me gebruiken",
      uninstall: "Om te de-installeren, rechtsklik het symbool van de webextensie",
      shareFacebook1: "% van de politieke advertenties die ik op Facebook zie zijn van ",
      shareFacebook2: ". Installeer Who Targets Me in uw browser en ontdek wie probeert uw stem te winnen door middel van doelgerichte social media advertenties. https://whotargets.me",
      shareTwitter1: "% van de politieke advertenties die ik op Facebook zie zijn van ",
      shareTwitter2: ". Installeer Who Targets Me in uw browser en ontdek wie probeert uw stem te winnen door middel van doelgerichte social media advertenties. https://whotargets.me",
      results_screen1: "U wordt benaderd door ", // You are being targeted by {party name}.
      results_screen2: "In totaal heeft u ", // In total you've seen {quantity} political ads,
      results_screen3: " politieke advertenties, waarvan ", //of which.
      results_screen4: " waren van ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'Website',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Voorwaarden',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacyverklaring',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  il: {
    who_targets_me: 'Who Targets Me?',
    loading: 'טוען, תודה על סבלנותך',
    register: {
      welcome1: 'Who Targets Me עוזרים לאנשים להבין איך פרסומות',
      welcome2: 'מותאמות אישית משמשות להשפעה על דעת הקהל',
      welcome3: 'עזרו לנו להראות לכם את הגרסה המתאימה של Who Targets Me',
      welcome4: 'כדי שנכיר את מערכת הבחירות הבאה שלכם',
      select_language: 'בחרו את השפה שלכם',
      terms: '<span>במעבר לשלב הבא אתם מסכימים ל <a href="https://whotargets.me/en/terms/">תנאי השימוש</a> ול <a href="https://whotargets.me/en/privacy-policy/">הצהרת הפרטיות</a></span>',
      agree: 'אני מסכימ/ה',
      back: 'הקודם',
      next: 'הבא',
      country: 'מדינה',
      enter_country: 'בחר/י את המדינה שלך',
      postcode: 'מיקוד',
      enter_postcode: 'הכניסו את המיקוד שלכם בבקשה',
      postcode_error: 'נראה שהכנסת מיקוד לא נכון',
      gender: 'מגדר',
      male: 'זכר',
      female: 'נקבה',
      other: 'אחר',
      years_of_age: 'מה גילך (בשנים)?',
      age: 'גיל',
      confirming: 'מאשרים את הפרטים שלך',
      request_error: 'The server responded with the following message:',
      unknown_error: 'תקלה לא ידועה, אם ההודעה חוזרת צרו איתנו קשר!',
      share: 'שתפו את הפרוייקט כדי לעזור לחבריכם ללמוד עוד על תעמולת הבחירות המותאמת שהם רואים.',
      share1: 'שתפו את התוצאות שלכם',
      share2: 'כדי לעזור לאחרים ללמוד על מודעות מותאמות אישית. ',
      share3: 'Over %i people in %s are taking part in Who Targets Me.',
      share4: 'Will you share the project and help us to get to %i?',
      shareOnFacebook: 'פייסבוק',
      shareOnTwitter: 'טוויטר',
      skip: 'דלג/י',
      shareFacebook: 'Who Targets Me חוקרים פרסום פוליטי ברשתות החברתיות. אני כבר עזרתי להם. הצטרפו אליי ותגלו גם מי מתאים לכם פרסומות: https://whotargets.me',
      shareTwitter: '@WhoTargetsMe חוקרים פרסום פוליטי ברשתות החברתיות. אני כבר עזרתי להם. הצטרפו אליי ותגלו גם מי מתאים לכם פרסומות: https://whotargets.me',
      political_affiliation: 'הדעות הפוליטיות שלך',
      political_affiliation_description: 'רוב האנשים חושבים על פוליטיקה בחלוקה של "שמאל" ו"ימין". איך היית מגדיר/ה את הדעות שלך?',
      us_labels: ['No affiliation', 'Very liberal', 'Moderately liberal', 'Slightly liberal', 'Center', 'Slightly conservative', 'Moderately conservative', 'Very conservative'],
      non_us_labels: ['אף אחת מהאפשרויות', 'שמאלני/ת מאוד', 'שמאל מתון', 'שמאל מרכז', 'מרכז', 'ימין מרכז', 'ימין מתון', 'ימני/ת מאוד'],
      would_rather_not_say: 'אעדיף לא להגיד',
      county: 'מדינה',
    },
    results: {
      my_constituency: 'My Constituency',
      constituency_size: 'You are one of %i volunteers in %s, can you help us reach %i?',
      constituency_size_one: 'You are the first volunteer in %s!. Can you help us find more?',
      no_results_explanation: 'התוצאות יוצגו כאן כשיהיה לנו מספיק מידע. המשיכו להשתמש בפייסבוק כרגיל ובדקו שוב בעוד מספר ימים.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "אם המידע שלך ימחק לא נוכל לבצע את המחקר. יש לך שלוש אפשרויות:",
      data_deleted: "המידע שלך נמחק ולא יאסף מידע נוסף",
      data_deleted2: "ניתן למחוק את התוסף בלחיצה ימנית על הסמל של Who Targets Me בסרגל הכלים בדפדפן שלך, ואז על 'מחק",
      data_deleted3: "שוב תודה על השתתפותך. תוכל/י להמשיך להתעדכן על הפרוייקט דרך טוויטר, פייסבוק ורשימת התפוצה שלנו.",
      delete_data: "מחיקת המידע",
      delete_data_message: "מוחקים את כל המידע שאספת עם Who Targets Me וגם את הפרופיל האנונימי שלך",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "לחצ/י עם הלחצן הימני על הסמל בדפדפן ובחר/י 'מחק'",
      remove_WTM_message2: "שומרים את המידע שלך ואת הפרופיל האנונימי למחקר",
      cancel: "ביטול",
      cancel_message: "חזרה למסך הקודם והמשך שימוש ב-Who Targets Me",
      uninstall: "לביטול ההתקנה, לחצו עם הלחצן הימני על הסמל",
      shareFacebook1: "% of the political ads I see on Facebook are from ",
      shareFacebook2: "התקינו את Who Targets Me בדפדפן שלכם כדי לגלות מי מנסה לקבל את הקול שלכם בעזרת מודעות מותאמות אישית ברשתות החברתיות. https://whotargets.me",
      shareTwitter1: "% of the political ads I see on Facebook are from ",
      shareTwitter2: "התקינו את Who Targets Me בדפדפן שלכם כדי לגלות מי מנסה לקבל את הקול שלכם בעזרת מודעות מותאמות אישית ברשתות החברתיות. https://whotargets.me",
      results_screen1: "את/ה מקבל/ת פרסומות מותאמות אישית מ ", // You are being targeted by {party name}.
      results_screen2: "בסך הכל ראית ", // In total you've seen {quantity} political ads,
      results_screen3: " political ads, of which ", //of which.
      results_screen4: " were from ", //{quantity} were from {party name}
    },
    links: {
      website: {
        title: 'אתר',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'תנאי שימוש',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'הצהרת פרטיות',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'פייסבוק',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'טוויטר',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  }
});

export const changeLocale = (locale) => {
  chrome.storage.promise.local.set({language: locale});
  strings.setLanguage(locale);
}

chrome.storage.promise.local.get('language')
  .then((result) => {
    strings.setLanguage(result.language);
  })
  .catch(() => {
    chrome.storage.promise.local.set({language: 'en'});
    strings.setLanguage('en');
  })

export default strings;
