import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  en: {
    who_targets_me: 'Who Targets Me?',
    loading: 'Loading, thank you for your patience',
    register: {
      select_language: 'Please select your preferred language',
      terms: '<span>By continuing you agree to the <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'I Agree',
      back: 'Back',
      next: 'Next',
      country: 'Country',
      enter_country: 'Please enter your country of residence',
      postcode: 'Postcode / Zipcode',
      enter_postcode: 'Please enter your postcode or zipcode',
      postcode_error: 'It looks like you entered an invalid postcode',
      gender: 'Your gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      years_of_age: 'How old are you (in years)?',
      age: 'Age',
      confirming: 'Confirming your details',
      request_error: 'The server responded with the following message:',
      unknown_error: 'Unknown error, if this persists please get in touch!',
      share: 'Share the project to help your friends learn more about the targeted political ads they see.',
      share1: 'Share the project',
      share2: ' to help your friends learn more about the targeted political ads they see.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Skip',
      shareFacebook: '@WhoTargetsMe is investigating dark advertising, find out who targets you https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe is investigating dark advertising, find out who targets you https://whotargets.me/',
      political_affiliation: 'Your political views',
      political_affiliation_description: 'Most people think of politics as having a \'left\' and a \'right\'. How would you describe your own views?',
      us_labels: ['No affiliation', 'Very liberal', 'Moderately liberal', 'Slightly liberal', 'Center', 'Slightly conservative', 'Moderately conservative', 'Very conservative'],
      non_us_labels: ['No affiliation', 'Very left wing', 'Moderately left wing', 'Slightly left wing', 'Center', 'Slightly right wing', 'Moderately right wing', 'Very right wing'],
      would_rather_not_say: 'Would rather not say',
      county: 'County',
    },
    results: {
      my_constituency: 'My Constituency',
      constituency_size: 'You are one of %i volunteers in %s, can you help us reach %i?',
      constituency_size_one: 'You are the first volunteer in %s!. Can you help us find more?',
      no_results_explanation: 'Results will appear here when we have enough data. Continue to use Facebook as normal and check back in a few days.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar",
      shareFacebook1: "I'm being targeted by ",
      shareFacebook2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
      shareTwitter1: "I'm being targeted by ",
      shareTwitter2: ". Install Who Targets Me to find out who's using political social media ads to win your vote. https://whotargets.me",
    },
    links: {
      website: {
        title: 'Website',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'T&Cs',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy Policy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  de: {
    who_targets_me: 'Wer bezahlt für meine Stimme?',
    loading: 'Daten werden geladen, vielen Dank für deine Geduld',
    register: {
      select_language: 'Bitte wählen Sie Ihre bevorzugte Sprache aus',
      terms: '<span>By continuing you agree to the <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'Ich stimme zu',
      back: 'Zurück',
      next: 'Nächster',
      country: 'Land',
      enter_country: 'Bitte geben Sie Ihr Land an',
      postcode: 'Postleitzahl',
      enter_postcode: 'Bitte geben Sie Ihre Postleitzahl ein',
      postcode_error: 'Es sieht so aus, als hätten Sie eine ungültige Postleitzahl eingegeben',
      gender: 'Dein Geschlecht',
      male: 'Männlich',
      female: 'Weiblich',
      other: 'Andere',
      years_of_age: 'Wie alt bist du (in Jahren)?',
      age: 'Alter',
      confirming: 'Bestätigen Sie Ihre Angaben',
      request_error: 'Der Server antwortete mit folgendem Fehler:',
      unknown_error: 'Unbekannter Fehler, falls anhalten Sie bitte in Kontakt!',
      share: 'Share Who Targets Me mit Ihren Freunden, um digitale Transparenz zu unterstützen',
      share1: 'Share the project',
      share2: ' to help your friends learn more about the targeted political ads they see.',
      shareOnFacebook: 'Facebook',
      shareOnTwitter: 'Twitter',
      skip: 'Überspringen',
      shareFacebook: '@WhoTargetsMe enthullt Dark Ads an der #BTW17 Finde heraus, welche Parteien auf dich zielen https://whotargets.me/de',
      shareTwitter: '@WhoTargetsMe enthullt Dark Ads an der #BTW17 Finde heraus, welche Parteien auf dich zielen https://whotargets.me/de',
      political_affiliation: 'Please choose your political affiliation',
    },
    results: {
      my_constituency: 'Mein Bundestagswahlkreis',
      constituency_size: 'Du bist einer von %i Freiwilligen in %s, kannst du uns helfen %i zu erreichen?',
      constituency_size_one: 'Glückwünsch! Du bist der/die erste/r Freiwillige in %s. Kannst du uns helfen, noch mehr zu finden?',
      no_results_explanation: 'Who Targets Me arbeitet im Hintergrund, um zu ermitteln, welche Werbung du siehst. Diese Seite wird mit Statistiken aktualisiert, sobald wir genug Daten gesammelt haben.',
      no_country_explanation1: "We'll be bringing personalised results to ",
      no_country_explanation2: " soon. In the meanwhile, continue to use Facebook as normal and thanks for taking part in Who Targets Me.",
      delete_request: "Deleting your data will make it unavailable for research. You have three choices:",
      data_deleted: "Your data has been deleted and no new data is being collected.",
      data_deleted2: "You can now remove the extension by right-clicking Who Targets Me icon in your browser toolbar, and selecting 'Remove...'",
      data_deleted3: "Thanks again for taking part. You can continue to follow updates on the project via Twitter, Facebook and our email list.",
      delete_data: "Delete data",
      delete_data_message: "Deletes all data you've gathered with Who Targets Me along with your anonymous profile.",
      remove_WTM: "Remove WTM",
      remove_WTM_message: "Right click the extension icon and select 'Remove...'",
      remove_WTM_message2: "Preserves your data and anonymous profile for research.",
      cancel: "Cancel",
      cancel_message: "Go back to the previous screen and continue using Who Targets Me",
      uninstall: "To uninstall, right-click the extension icon on your toolbar"
    },
    links: {
      website: {
        title: 'Webseite',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Bedingungen',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privatsphäre',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  es: {
    who_targets_me: '¿De quién soy el blanco?',
    loading: 'Cargando, gracias por su paciencia',
    register: {
      select_language: 'Por favor seleccione su idioma',
      terms: '<span>Al continuar usted acepta las <a href="https://whotargets.me/en/terms/">terms and conditions</a> and <a href="https://whotargets.me/en/privacy-policy/">privacy policy</a></span>',
      agree: 'Acepto',
      back: 'Volver',
      next: 'Siguiente',
      country: 'País',
      enter_country: 'Por favor ingrese su país de residencia',
      postcode: 'Tu género',
      enter_postcode: 'Por favor ingrese su código postal',
      postcode_error: 'Parece que ingresaste un código postal no válido.',
      gender: 'Tu género',
      male: 'Hombre',
      female: 'Mujer',
      other: 'Otro',
      years_of_age: '¿Qué edad tiene usted (en años)?',
      age: 'Edad',
      confirming: 'Confirmando sus datos de registro',
      request_error: 'El servidor a respondido con el siguiente mensaje:',
      unknown_error: 'Error desconocido, ¡Si persiste por favor contáctenos!',
      share: 'Comparte ¿De quién soy el blanco? con tus amigos para apoyar la transparencia digital',
      shareOnFacebook: 'Compartir en Facebook',
      shareOnTwitter: 'Compartir en Twitter',
      skip: 'Saltar',
      shareFacebook: '@WhoTargetsMe esta investigando publicidad oculta, averigua de quien eres blanco https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe esta investigando publicidad oculta, averigua de quien eres blanco https://whotargets.me/',
    },
    results: {
      my_constituency: 'Mi circunscripción',
      constituency_size: 'Eres uno de %i voluntario de %s, ¿Puedes ayudarnos a alcanzar %i?',
      constituency_size_one: 'Eres el primer voluntario de %s!. ¿Puedes ayudarnos a averiguar más?',
      no_results_explanation: '¿De quién eres blanco? opera en segundo plano para determinar que publicidad ves. Esta página se actualizara con estadísticas tan pronto hayamos recopilado suficientes información.',
    },
    links: {
      website: {
        title: 'Página Web',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Terminos',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacidad',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  it: {
    who_targets_me: 'Who Targets Me?',
    loading: 'In caricamento, grazie per la pazienza',
    register: {
      select_language: 'Seleziona la tua lingua preferita',
      terms: '<span>Procedendo con la registrazione accetti <a href="https://whotargets.me/en/terms/">i termini di utilizzo</a> e <a href="https://whotargets.me/en/privacy-policy/">la privacy policy</a></span>',
      agree: 'Accetto',
      back: 'Indietro',
      next: 'Prossimo',
      country: 'Paese',
      enter_country: 'Inserisci il tuo Paese di residenza',
      postcode: 'CAP',
      enter_postcode: 'Inserisci il tuo CAP',
      postcode_error: 'Il CAP inserito non sembra essere valido',
      gender: 'Il tuo genere',
      male: 'Uomo',
      female: 'Donna',
      other: 'Altro',
      years_of_age: 'Quanti anni hai?',
      age: 'Età',
      confirming: 'Conferma i dettagli inseriti',
      request_error: 'Il server ha restituito il seguente messaggio:',
      unknown_error: 'Errore sconosciuto, se dovesse accadere di nuovo non esitare a contattarci!',
      share: 'Condividi Who Targets Me con i tuoi amici per supportare la trasparenza digitale',
      shareOnFacebook: 'Condividi su Facebook',
      shareOnTwitter: 'Condividi su Twitter',
      skip: 'Salta',
      shareFacebook: '@WhoTargetsMe svela chi sta utilizzando campagne pubblicitarie politiche oscure. Scopri chi ti sta prendendo di mira https://whotargets.me/',
      shareTwitter: '@WhoTargetsMe svela chi sta utilizzando campagne pubblicitarie politiche oscure. Scopri chi ti sta prendendo di mira https://whotargets.me/',
    },
    results: {
      my_constituency: 'La mia circoscrizione',
      constituency_size: 'Sei uno dei %i volontari nella tua circoscrizione (%s), puoi aiutarci a raggiungerne %i?',
      constituency_size_one: 'Tu sei il primo volontario in %s!. Puoi aiutarci a trovarne altri?',
      no_results_explanation: 'Who Targets Me lavora in modo nascosto per determinare quali messaggi pubblicitari vedi. Questa pagina sarà aggiornata con le statistiche non appena avremo collezionato dati a sufficienza.',
    },
    links: {
      website: {
        title: 'Sito web',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Termini di utilizzo',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Privacy',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
  hu: {
    who_targets_me: 'Célkeresztben',
    loading: 'Az oldal töltődik, kis türelmet kérünk',
    register: {
      select_language: 'Válasszon nyelvet',
      terms: '<span>A folytatással elfogadja a <a href="https://whotargets.me/en/terms/">felhasználási feltételeket</a> és <a href="https://whotargets.me/en/privacy-policy/">az adatkezelési irányelveket</a></span>',
      agree: 'Elfogadom',
      back: 'Vissza',
      next: 'Tovább',
      country: 'Ország',
      enter_country: 'Tartózkodási ország',
      postcode: 'Irányítószám',
      enter_postcode: 'Adja meg az irányítószámát',
      postcode_error: 'Az irányítószám formátuma nem megfelelő',
      gender: 'Nemed',
      male: 'Férfi',
      female: 'Nő',
      other: 'Egyéb',
      years_of_age: 'Hány éves?',
      age: 'Kor',
      confirming: 'Adataim megerősítése',
      request_error: 'A szerver a következő üzenettel tért vissza:',
      unknown_error: 'Ismeretlen hiba, ha továbbra is ezt tapasztalja, lépjen velünk kapcsolatba!',
      share: 'Segítsen növelni a digitális átláthatóságot! Ossza meg a Célkeresztben alkalmazást az ismerőseivel.',
      shareOnFacebook: 'Megosztom a Facebookon',
      shareOnTwitter: 'Megosztom a Twitteren',
      skip: 'Ezt most kihagyom',
      shareFacebook: 'A @WhoTargetsMe az online hirdetések sötét oldalát vizsgálja. Nézze meg, Önnek ki üzen. https://whotargets.me/',
      shareTwitter: 'A @WhoTargetsMe az online hirdetések sötét oldalát vizsgálja. Nézze meg, Önnek ki üzen. https://whotargets.me/',
      political_affiliation: 'Melyik politikai oldal áll Önhöz a legközelebb?',
      political_affiliation_description: 'A legtöbben jobb- és baloldalról beszélnek a politikában. Ön hogyan írná le a nézeteit?',
      us_labels: ['No affiliation', 'Erőteljesen baloldali', 'Mérsékelten baloldali', 'Kissé baloldali', 'Centrista', 'Kissé jobboldali', 'Mérsékelten jobboldali', 'Erőteljesen jobboldali'],
      non_us_labels: ['No affiliation', 'Erőteljesen baloldali', 'Mérsékelten baloldali', 'Kissé baloldali', 'Centrista', 'Kissé jobboldali', 'Mérsékelten jobboldali', 'Erőteljesen jobboldali'],
      would_rather_not_say: 'Nem akarok mondani',
    },
    results: {
      my_constituency: 'Választókörzetem',
      constituency_size: '%s körzetben %i önkéntesünk van, segítsen nekünk elérni, hogy ennyi legyen: %i!',
      constituency_size_one: 'Ön az első önkéntes itt: %s. Hívjon meg másokat is!',
      no_results_explanation: 'A Célkeresztben alkalmazás a háttérben fut, hogy azonosítsa, milyen hirdetéseket mutat Önnek a Facebook. Ezen az oldalon jelennek meg a statisztikák, amint elég adatot gyűjtöttünk.',
    },
    links: {
      website: {
        title: 'Honlap',
        url: 'https://whotargets.me',
      },
      terms: {
        title: 'Felhasználási feltételek',
        url: 'https://whotargets.me/terms',
      },
      privacy: {
        title: 'Adatvédelem',
        url: 'https://whotargets.me/privacy-policy',
      },
      facebook: {
        title: 'Facebook',
        url: 'https://www.facebook.com/whotargetsme/',
      },
      twitter: {
        title: 'Twitter',
        url: 'https://twitter.com/whotargetsme',
      },
    },
  },
});

export const changeLocale = (locale) => {
  chrome.storage.promise.local.set({language: locale});
  strings.setLanguage(locale);
}

chrome.storage.promise.local.get('language')
  .then((result) => {
    strings.setLanguage(result.language);
  })
  .catch(() => {
    chrome.storage.promise.local.set({language: 'en'});
    strings.setLanguage('en');
  })

export default strings;
