name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dispatch testing event
        uses: peter-evans/repository-dispatch@v2
        if: github.event.pull_request.merged
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          repository: WhoTargetsMe/wtm-testing
          event-type: test-event
