name: Tests CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: executing tests in wtm-testing
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: WhoTargetsMe
          repo: wtm-testing
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: test.yml
          wait_interval: 90